import {
  Component,
  inject,
  OnInit,
  OnDestroy,
  signal,
  computed,
  effect,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subject, Subscription, firstValueFrom, takeUntil } from 'rxjs';
import { ScheduleStore } from '../../core/state';
import { UNIT_COLORS } from '../../domain/rules';
import { type UnitType } from '../../domain/enums';
import { type ShiftAssignment } from '../../domain/models';
import {
  ScheduleService,
  type ScheduleResponse,
  type ScheduleAlert,
} from '../../services/schedule.service';
import { ApiService } from '../../core/api/api.service';
import { NotificationService } from '../../services/notification.service';
import { WebSocketService } from '../../services/websocket.service';
import { AuthService } from '../../services/auth.service';
import {
  getHoliday,
  getHolidayCountForMonth,
  isHoliday,
  HOLIDAY_COLORS,
} from '../../core/calendar/turkish-holidays';
import { ScheduleGridComponent } from '../../components/schedule-grid/schedule-grid.component';
import { ScheduleAlertsComponent } from '../../components/schedule-alerts/schedule-alerts.component';
import { AutoGenerateDialogComponent } from '../../components/auto-generate-dialog/auto-generate-dialog.component';
import { AssignmentDialogComponent } from '../../components/assignment-dialog/assignment-dialog.component';
import { PersonShiftViewComponent } from '../../components/person-shift-view/person-shift-view.component';
import {
  shiftsMatch,
  shiftNameTR,
  formatDateTR,
  deviceBookedMessageFor,
} from '../../core/utils/assignment-errors';

type ViewState =
  | { status: 'loading' }
  | { status: 'success'; schedule: ScheduleResponse }
  | { status: 'empty'; reason?: string }
  | { status: 'error'; message: string; code: number; endpoint?: string };

function mapHttpError(err: unknown): { message: string; code: number; endpoint?: string } {
  const map: Record<number, string> = {
    500: 'Sistemsel hata oluştu. Plan verileri alınamadı.',
    404: 'Bu birim için plan bulunamadı.',
    403: 'Bu işlem için yetkiniz bulunmuyor.',
    401: 'Oturum süreniz doldu. Lütfen tekrar giriş yapın.',
    400: 'Geçersiz istek. Lütfen sayfayı yenileyip tekrar deneyin.',
    0: 'Sunucuya ulaşılamıyor. Lütfen bağlantınızı kontrol edin.',
  };
  const e = err as { statusCode?: number; status?: number; message?: string; path?: string };
  const code = e?.statusCode ?? e?.status ?? 0;
  return {
    code,
    message: map[code] || e?.message || 'Beklenmeyen bir hata oluştu.',
    endpoint: e?.path,
  };
}

interface DayColumn {
  date: Date;
  dateStr: string;
  dayNumber: number;
  dayName: string;
  dayNum: number;
  isWeekend: boolean;
  isHoliday: boolean;
  holidayName?: string;
  holidayType?: string;
  isToday: boolean;
}

interface DeviceShiftInfo {
  type: string;
  startTime: string;
  endTime: string;
  name: string;
  personnelType: string | null;
}

interface DeviceInfo {
  id: string;
  code: string;
  name: string;
  mode: 'vardiya' | 'polyclinic';
  tripleShift: boolean;
  shifts: DeviceShiftInfo[];
}

interface DragAssignment {
  deviceId: string;
  date: string;
  shiftType: string;
  personnelId?: string;
  personnelName?: string;
  personnelType?: string | null;
}

interface DragState {
  isDragging: boolean;
  sourceAssignment: DragAssignment | null;
  targetSlot: { deviceId: string; date: string; shiftType: string } | null;
  isValid: boolean;
}

interface UnitPlanConfig {
  accentColor: string;
  metricDefs: Array<{
    key: string;
    label: string;
    calc: (assignments: ShiftAssignment[], devices: number, vs: ScheduleResponse) => number;
    formatter?: (v: number) => string;
  }>;
  tooltipExtraFields: Array<{ key: string; label: string; get: (a: ShiftAssignment) => string }>;
  legendItems: Array<{ label: string; cssClass: string }>;
  onboardingHint: string;
  compactLayout: boolean;
}

const UNIT_PLAN_CONFIGS: Record<string, UnitPlanConfig> = {
  mr: {
    accentColor: '#3b82f6',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const totalShiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          return dim * totalShiftsPerDay;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'unassigned',
        label: 'Atanmamış',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const totalShiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          return dim * totalShiftsPerDay - a.length;
        },
      },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const totalShiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          const tot = dim * totalShiftsPerDay;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'criticalGaps',
        label: 'Kritik Boşluk',
        calc: (a) => {
          const today = new Date().toISOString().split('T')[0];
          const three = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];
          const near = a.filter((x) => x.date >= today && x.date <= three).length;
          return Math.max(0, near - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'İzin', cssClass: 'izin-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: '+ ikonuna tıklayarak MR vardiyası atayın',
    compactLayout: false,
  },
  bt: {
    accentColor: '#06b6d4',
    metricDefs: [
      {
        key: 'contrastRate',
        label: 'Kontrastlı Çekim',
        calc: (a) => {
          const contr = a.filter((x) => (x as any).protocol?.includes('kontrast')).length;
          return a.length > 0 ? Math.round((contr / a.length) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'emergencyDensity',
        label: 'Acil Vaka',
        calc: (a) => a.filter((x) => (x as any).protocol?.includes('acil')).length,
      },
      {
        key: 'usageRate',
        label: 'Kullanım',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const totalShiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          const tot = dim * totalShiftsPerDay;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'emptyAlarm',
        label: 'Boş Slot Alarmı',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const totalShiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          return Math.max(0, dim * totalShiftsPerDay - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [
      { key: 'protocol', label: 'Protokol', get: (a) => (a as any).protocol || 'Standart' },
      {
        key: 'contrast',
        label: 'Kontrast',
        get: (a) => ((a as any).contrastRequired ? 'Gerekli' : 'Yok'),
      },
      { key: 'avgDuration', label: 'Ort. Süre', get: () => '~12dk' },
    ],
    legendItems: [
      { label: 'Acil BT', cssClass: 'acil-bt-swatch' },
      { label: 'Rutin BT', cssClass: 'rutin-bt-swatch' },
      { label: 'Kontrastlı', cssClass: 'kontrastli-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Bakım', cssClass: 'bakim-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'BT cihaz slotlarını teknisyenlerle eşleştirin',
    compactLayout: false,
  },
  rontgen: {
    accentColor: '#f59e0b',
    metricDefs: [
      { key: 'dailyThroughput', label: 'Hasta Throughput', calc: (a) => a.length },
      {
        key: 'portableDensity',
        label: 'Portable Çekim',
        calc: (a) => a.filter((x) => (x as any).equipment === 'portable').length,
      },
      {
        key: 'serviceDist',
        label: 'Servis Dağılımı',
        calc: (a) => Math.round(a.length / Math.max(1, new Set(a.map((x) => x.deviceId)).size)),
      },
      { key: 'waitTime', label: 'Bekleme Süresi', calc: () => 0, formatter: () => '~0dk' },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [
      {
        key: 'equipment',
        label: 'Ekipman',
        get: (a) => ((a as any).equipment === 'portable' ? 'Portable' : 'Sabit'),
      },
      { key: 'location', label: 'Lokasyon', get: (a) => (a as any).location || 'Ana Bölüm' },
      { key: 'estDuration', label: 'Tahmini Süre', get: () => '~8dk' },
    ],
    legendItems: [
      { label: 'Direkt Grafi', cssClass: 'direkt-grafi-swatch' },
      { label: 'Portable', cssClass: 'portable-swatch' },
      { label: 'Acil', cssClass: 'rontgen-acil-swatch' },
      { label: 'Boş', cssClass: 'rontgen-bos-swatch' },
      { label: 'Arıza', cssClass: 'ariza-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Servis yoğunluğunu dengelemek için vardiya atayın',
    compactLayout: true,
  },
  nukleer: {
    accentColor: '#10b981',
    metricDefs: [
      { key: 'radioSlotUsage', label: 'Radyofarmasötik Slot', calc: (a) => a.length },
      {
        key: 'delayedTracking',
        label: 'Gecikmeli Çekim',
        calc: (a) => a.filter((x) => (x as any).status === 'delayed').length,
      },
      {
        key: 'prepStatus',
        label: 'Hasta Hazırlık',
        calc: (a) => {
          const ready = a.filter((x) => (x as any).prepStatus === 'ready').length;
          return a.length > 0 ? Math.round((ready / a.length) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'criticalGap',
        label: 'Kritik Boşluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return Math.max(0, dim * dev - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [
      { key: 'isotope', label: 'İzotop', get: (a) => (a as any).isotope || 'Tc-99m' },
      { key: 'waitTime', label: 'Bekleme', get: (a) => (a as any).waitTime || '~30dk' },
      {
        key: 'prepReady',
        label: 'Hazırlık',
        get: (a) => ((a as any).prepStatus === 'ready' ? 'Hazır' : 'Beklemede'),
      },
    ],
    legendItems: [
      { label: 'Sintigrafi', cssClass: 'sintigrafi-swatch' },
      { label: 'PET Hazırlık', cssClass: 'pet-hazirlik-swatch' },
      { label: 'Bekleme', cssClass: 'nukleer-bekleme-swatch' },
      { label: 'Boş', cssClass: 'nukleer-bos-swatch' },
      { label: 'İzolasyon', cssClass: 'izolasyon-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Hazırlık sürelerini dikkate alarak slot planlayın',
    compactLayout: false,
  },

  ultrason: {
    accentColor: '#ec4899',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'criticalGaps',
        label: 'Kritik Boşluk',
        calc: (a) => {
          const today = new Date().toISOString().split('T')[0];
          const three = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];
          const near = a.filter((x) => x.date >= today && x.date <= three).length;
          return Math.max(0, near - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Ultrason cihazlarına vardiya atayın',
    compactLayout: false,
  },

  anjiyo: {
    accentColor: '#ef4444',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'emergencyDensity',
        label: 'Acil Vaka',
        calc: (a) => a.filter((x) => (x as any).protocol?.includes('acil')).length,
      },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Acil', cssClass: 'acil-bt-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Acil anjiyo vakaları için hazırda personel bulundurun',
    compactLayout: false,
  },

  mamografi: {
    accentColor: '#d946ef',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'screeningRate',
        label: 'Tarama Oranı',
        calc: (a) =>
          a.length > 0
            ? Math.round(
                (a.filter((x) => (x as any).protocol?.includes('tarama')).length / a.length) * 100,
              )
            : 0,
        formatter: (v) => `${v}%`,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Tarama', cssClass: 'sintigrafi-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Mamografi tarama ve tanı vardiyalarını planlayın',
    compactLayout: false,
  },

  kemik_dansitometri: {
    accentColor: '#14b8a6',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Kemik dansitometri vardiyalarını planlayın',
    compactLayout: false,
  },

  floroskopi: {
    accentColor: '#f97316',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'contrastUsage',
        label: 'Kontrastlı',
        calc: (a) => a.filter((x) => (x as any).protocol?.includes('kontrast')).length,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Kontrastlı', cssClass: 'kontrastli-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Floroskopi işlemleri için vardiya planlayın',
    compactLayout: false,
  },

  pet_ct: {
    accentColor: '#8b5cf6',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'fdgPrep',
        label: 'FDG Hazırlık',
        calc: (a) => a.filter((x) => (x as any).protocol?.includes('fdg')).length,
      },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'FDG Hazırlık', cssClass: 'pet-hazirlik-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'FDG hazırlık sürelerini dikkate alarak plan yapın',
    compactLayout: false,
  },

  spect_ct: {
    accentColor: '#6366f1',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'SPECT CT vardiyalarını planlayın',
    compactLayout: false,
  },

  linak: {
    accentColor: '#e11d48',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Fraksiyon',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Planlanan', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'criticalGaps',
        label: 'Kritik Boşluk',
        calc: (a) => {
          const today = new Date().toISOString().split('T')[0];
          const three = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];
          const near = a.filter((x) => x.date >= today && x.date <= three).length;
          return Math.max(0, near - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Linak fraksiyon planlaması için vardiya atayın',
    compactLayout: false,
  },

  simutasyon_ct: {
    accentColor: '#0ea5e9',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Simülasyon CT için vardiya planlayın',
    compactLayout: false,
  },

  mobil: {
    accentColor: '#64748b',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const tot = dim * dev * 2;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'portableRate',
        label: 'Portable',
        calc: (a) => a.filter((x) => (x as any).equipment === 'portable').length,
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Mobil', cssClass: 'portable-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Mobil cihaz vardiyalarını planlayın',
    compactLayout: false,
  },

  onkoloji: {
    accentColor: '#e11d48',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Fraksiyon',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          return dim * dev * 2;
        },
      },
      { key: 'assigned', label: 'Planlanan', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const totalShiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          const tot = dim * totalShiftsPerDay;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'criticalGaps',
        label: 'Kritik Boşluk',
        calc: (a) => {
          const today = new Date().toISOString().split('T')[0];
          const three = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];
          const near = a.filter((x) => x.date >= today && x.date <= three).length;
          return Math.max(0, near - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Radyoterapi fraksiyon planlaması için vardiya atayın',
    compactLayout: false,
  },

  supervizor: {
    accentColor: '#8b5cf6',
    metricDefs: [
      {
        key: 'totalSlots',
        label: 'Toplam Slot',
        calc: (_, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const shiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          return dim * shiftsPerDay;
        },
      },
      { key: 'assigned', label: 'Atanmış', calc: (a) => a.length },
      {
        key: 'occupancyPct',
        label: 'Doluluk',
        calc: (a, dev, vs) => {
          const dim = new Date(vs.year, vs.month, 0).getDate();
          const shiftsPerDay =
            (vs.deviceShiftConfig || []).reduce((sum, d) => {
              const types = new Set(
                d.shifts.map((s: any) => `${s.type}|${s.personnelType || 'default'}`),
              );
              return sum + Math.max(types.size, 1);
            }, 0) || dev * 2;
          const tot = dim * shiftsPerDay;
          return tot > 0 ? Math.round((a.length / tot) * 100) : 0;
        },
        formatter: (v) => `${v}%`,
      },
      {
        key: 'criticalGaps',
        label: 'Kritik Boşluk',
        calc: (a) => {
          const today = new Date().toISOString().split('T')[0];
          const three = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];
          const near = a.filter((x) => x.date >= today && x.date <= three).length;
          return Math.max(0, near - a.length);
        },
      },
      {
        key: 'holidayCount',
        label: 'Tatil Günü',
        calc: (_, __, vs) => getHolidayCountForMonth(vs.year, vs.month),
        formatter: (v) => `${v} gün`,
      },
    ],
    tooltipExtraFields: [],
    legendItems: [
      { label: 'Gündüz', cssClass: 'gunduz-swatch' },
      { label: 'Gece', cssClass: 'gece-swatch' },
      { label: 'Boş Slot', cssClass: 'bos-swatch' },
      { label: 'Resmî Tatil', cssClass: 'tatil-swatch' },
      { label: 'Dini Bayram', cssClass: 'tatil-swatch-religious' },
    ],
    onboardingHint: 'Süpervizör nöbet planlaması için atama yapın',
    compactLayout: false,
  },
};

function computeFairnessScore(assignments: ShiftAssignment[]): number {
  if (assignments.length === 0) return 100;
  const keyOf = (a: ShiftAssignment) => a.personnelId || a.personnelName || 'Bilinmeyen';
  const totals = new Map<string, number>();
  const nights = new Map<string, number>();
  for (const a of assignments) {
    const k = keyOf(a);
    totals.set(k, (totals.get(k) || 0) + 1);
    const st = (a.shiftType || '').toLowerCase();
    if (
      st === 'gece' ||
      st === 'night' ||
      st === 'aksam' ||
      st === 'akşam' ||
      st === 'evening' ||
      st.includes('gece')
    ) {
      nights.set(k, (nights.get(k) || 0) + 1);
    }
  }
  const distScore = (m: Map<string, number>): number => {
    const counts = [...m.values()];
    if (counts.length === 0) return 100;
    const mean = counts.reduce((s, c) => s + c, 0) / counts.length;
    if (mean <= 0) return 100;
    const avgDev = counts.reduce((s, c) => s + Math.abs(c - mean), 0) / counts.length / mean;
    return Math.max(0, Math.round(100 - avgDev * 100));
  };
  const totalScore = distScore(totals);
  const nightScore = nights.size > 0 ? distScore(nights) : totalScore;
  return Math.round(totalScore * 0.7 + nightScore * 0.3);
}

function computeFairnessBreakdown(assignments: ShiftAssignment[]): string[] {
  const keyOf = (a: ShiftAssignment) => a.personnelId || a.personnelName || 'Bilinmeyen';
  const totals = new Map<string, number>();
  const nights = new Map<string, number>();
  for (const a of assignments) {
    const k = keyOf(a);
    totals.set(k, (totals.get(k) || 0) + 1);
    const st = (a.shiftType || '').toLowerCase();
    if (
      st === 'gece' ||
      st === 'night' ||
      st === 'aksam' ||
      st === 'akşam' ||
      st === 'evening' ||
      st.includes('gece')
    ) {
      nights.set(k, (nights.get(k) || 0) + 1);
    }
  }
  const nightOf = (k: string) => nights.get(k) || 0;
  return [...totals.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(
      ([name, total]) =>
        `${name}: ${total} vardiya${nightOf(name) ? ` (${nightOf(name)} gece)` : ''}`,
    );
}

@Component({
  selector: 'app-plan-page',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    CommonModule,
    FormsModule,
    ScheduleGridComponent,
    ScheduleAlertsComponent,
    AutoGenerateDialogComponent,
    AssignmentDialogComponent,
    PersonShiftViewComponent,
  ],
  templateUrl: './plan-page.component.html',
  styleUrls: ['./plan-page.component.scss'],
})
export class PlanPageComponent implements OnInit, OnDestroy {
  private readonly scheduleStore = inject(ScheduleStore);
  private readonly scheduleApi = inject(ScheduleService);
  private readonly api = inject(ApiService);
  private readonly notification = inject(NotificationService);
  private readonly websocket = inject(WebSocketService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly auth = inject(AuthService);
  private readonly destroy$ = new Subject<void>();
  private loadSub: Subscription | null = null;
  private lastUpdated: Date | null = null;
  private readonly loadEffect = effect(() => {
    this.loadPlan(
      this.selectedUnit(),
      this.scheduleStore.selectedMonth(),
      this.scheduleStore.selectedYear(),
    );
  });

  selectedUnit = signal<UnitType>('mr');
  activeTab = signal<'device' | 'person'>('device');
  viewState = signal<ViewState>({ status: 'loading' });
  readonly dragState = signal<DragState>({
    isDragging: false,
    sourceAssignment: null,
    targetSlot: null,
    isValid: false,
  });
  showLeftFade = signal(false);
  showRightFade = signal(true);
  clipboardAssignment = signal<{
    personnelId: string;
    personnelName: string;
    shiftType: string;
    personnelType?: string | null;
  } | null>(null);
  hasClipboard = computed(() => !!this.clipboardAssignment());
  showMonthPicker = signal(false);
  pickerMonth = signal(1);
  pickerYear = signal(2026);

  alerts = signal<ScheduleAlert[]>([]);
  alertsLoading = signal(false);
  showAutoGenerate = signal(false);

  // Monthly assignment
  showMonthlyAssign = signal(false);
  monthlyDeviceId = signal('');
  monthlyShiftType = signal('');
  monthlyPersonnelId = signal('');
  monthlyPersonnel = signal<{ id: string; name: string; skills?: string[] }[]>([]);
  monthlyBusy = signal(false);
  monthlyResult = signal('');
  monthlyShiftOptions = computed(() => {
    const device = this.devices().find((d) => d.id === this.monthlyDeviceId());
    return device ? device.shifts : [];
  });
  monthlyPersonnelFiltered = computed(() => {
    const q = this.monthlySearch().toLowerCase();
    return this.monthlyPersonnel().filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        (p.skills || []).some((s) => s.toLowerCase().includes(q)),
    );
  });
  monthlySearch = signal('');
  monthlyPersonnelLabel = computed(() => {
    const p = this.monthlyPersonnel().find((x) => x.id === this.monthlyPersonnelId());
    return p ? p.name : 'Personel seçin';
  });

  // Hover tooltip
  tooltipVisible = signal(false);
  tooltipX = signal(0);
  tooltipY = signal(0);
  tooltipAssignment = signal<ShiftAssignment | null>(null);

  // Onboarding hint
  onboardingKey = computed(() => `${this.selectedUnit()}-plan-onboarding-dismissed`);
  _onboardingDismissed = signal(false);
  showOnboarding = computed(
    () => !this._onboardingDismissed() && localStorage.getItem(this.onboardingKey()) !== 'true',
  );

  dismissOnboarding(): void {
    this._onboardingDismissed.set(true);
    localStorage.setItem(this.onboardingKey(), 'true');
  }

  // View mode toggle
  viewMode = signal<'grid' | 'list'>('grid');

  // List view search & filters
  searchQuery = signal('');
  filterShiftType = signal('');
  filterPersonnel = signal('');

  // Grid view controls
  deviceSearch = signal('');
  filterRole = signal('');
  filterStatus = signal('');
  showEmptyOnly = signal(false);
  density = signal<'compact' | 'normal' | 'comfortable'>('normal');

  // Dismissed API alerts (persist for session)
  resolvedAlerts = signal<Set<string>>(new Set());

  // Context menu
  contextMenu = signal<{
    visible: boolean;
    x: number;
    y: number;
    deviceId: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    personnelName?: string;
    personnelId?: string;
    startTime?: string;
    endTime?: string;
  } | null>(null);

  // Conflicts modal
  conflictsOpen = signal(false);
  conflictsList = signal<
    Array<{
      personName: string;
      entries: Array<{
        deviceId: string;
        deviceCode: string;
        deviceName: string;
        date: string;
        shiftType: string;
      }>;
    }>
  >([]);

  conflictCount = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return 0;
    const map = new Map<string, Map<string, number>>();
    for (const a of vs.schedule.assignments) {
      if (!a.personnelId) continue;
      if (!map.has(a.personnelId)) map.set(a.personnelId, new Map());
      const dm = map.get(a.personnelId)!;
      dm.set(a.date, (dm.get(a.date) || 0) + 1);
    }
    let count = 0;
    for (const dm of map.values()) {
      if ([...dm.values()].some((n) => n > 1)) count++;
    }
    return count;
  });

  totalFilterCount = computed(() => {
    let n = 0;
    if (this.deviceSearch()) n++;
    if (this.filterShiftType()) n++;
    if (this.filterRole()) n++;
    if (this.filterStatus()) n++;
    if (this.searchQuery()) n++;
    if (this.filterPersonnel()) n++;
    if (this.showEmptyOnly()) n++;
    return n;
  });

  deviceFullNameMap = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return new Map<string, string>();
    return new Map(vs.schedule.devices.map((d) => [d.id, d.name]));
  });

  personnelTypeLabels(): Record<string, string> {
    return {
      assistant_technician: 'Yardımcı Tekniker',
      technician: 'Tekniker',
      technician_2: 'Tekniker',
      technician_3: 'Tekniker',
      technician_4: 'Tekniker',
      senior_technician: 'Sorumlu Tekniker',
      supervisor: 'Süpervizör',
      medical_engineer: 'Medikal Mühendis',
      medical_physicist: 'Sağlık Fizikçisi',
      medical_physicist_2: 'Sağlık Fizikçisi',
      medical_physicist_3: 'Sağlık Fizikçisi',
      planning: 'Planlama',
    };
  }

  roleOptions = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return [];
    const set = new Set<string>();
    for (const s of vs.schedule.deviceShiftConfig || []) {
      for (const sh of s.shifts) {
        if (sh.personnelType)
          set.add(this.personnelTypeLabels()[sh.personnelType] || sh.personnelType);
      }
    }
    return [...set].sort();
  });

  statusOptions: Array<{ key: string; label: string }> = [
    { key: 'planned', label: 'Planlandı' },
    { key: 'confirmed', label: 'Onaylandı' },
    { key: 'completed', label: 'Tamamlandı' },
  ];

  resetAllFilters(): void {
    this.deviceSearch.set('');
    this.filterShiftType.set('');
    this.filterRole.set('');
    this.filterStatus.set('');
    this.showEmptyOnly.set(false);
    this.searchQuery.set('');
    this.filterPersonnel.set('');
  }

  // Device name map for list view
  deviceNameMap = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return new Map<string, string>();
    return new Map(vs.schedule.devices.map((d) => [d.id, d.code]));
  });

  // Unique personnel names for filter dropdown
  personnelNames = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return [];
    return Array.from(new Set(vs.schedule.assignments.map((a) => a.personnelName || ''))).sort();
  });

  // Flat assignment list
  assignmentsList = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return [];
    return vs.schedule.assignments;
  });

  // Filtered assignments for list view
  filteredAssignments = computed(() => {
    let list = this.assignmentsList();
    const q = this.searchQuery().toLowerCase();
    const st = this.filterShiftType();
    const pn = this.filterPersonnel();
    const role = this.filterRole();
    const status = this.filterStatus();
    if (q)
      list = list.filter(
        (a) => (a.personnelName || '').toLowerCase().includes(q) || a.date.includes(q),
      );
    if (st) list = list.filter((a) => this.shiftTypeMatches(a.shiftType, st));
    if (pn) list = list.filter((a) => (a.personnelName || '') === pn);
    if (role)
      list = list.filter(
        (a) =>
          (this.personnelTypeLabels()[a.personnelType || ''] || a.personnelType || '') === role,
      );
    if (status)
      list = list.filter((a) => (a.status || (a.isConfirmed ? 'confirmed' : 'planned')) === status);
    return list;
  });

  // Active filter count
  activeFilterCount = computed(() => {
    let count = 0;
    if (this.searchQuery()) count++;
    if (this.filterShiftType()) count++;
    if (this.filterPersonnel()) count++;
    return count;
  });

  resetFilters(): void {
    this.searchQuery.set('');
    this.filterShiftType.set('');
    this.filterPersonnel.set('');
  }

  // Assignment validation warnings
  validationWarnings = computed(() => {
    const warnings: Array<{
      type: string;
      message: string;
      severity: 'warning' | 'error';
      date?: string;
      deviceId?: string;
      shiftType?: string;
      alertKey: string;
    }> = [];
    const vs = this.viewState();
    if (vs.status !== 'success') return warnings;
    const assignments = vs.schedule.assignments;

    // Double assignment same day
    const personDayMap = new Map<string, string[]>();
    for (const a of assignments) {
      if (!a.personnelId) continue;
      const key = `${a.personnelId}|${a.date}`;
      if (!personDayMap.has(key)) personDayMap.set(key, []);
      personDayMap.get(key)!.push(a.shiftType);
    }
    for (const [key, shifts] of personDayMap) {
      if (shifts.length > 1) {
        const [pid, date] = key.split('|');
        const name = assignments.find((a) => a.personnelId === pid)?.personnelName || pid;
        warnings.push({
          type: 'double',
          message: `${name}: ${date} tarihinde ${shifts.length} vardiya`,
          severity: 'error',
          date,
          alertKey: `double|${key}`,
        });
      }
    }

    // Night-to-day rest violation
    const nightPersonnel = new Map<string, Set<string>>();
    for (const a of assignments) {
      const s = a.shiftType.toLowerCase();
      if (s.includes('night') || s.includes('gece') || a.startTime >= '20') {
        if (!nightPersonnel.has(a.personnelId)) nightPersonnel.set(a.personnelId, new Set());
        nightPersonnel.get(a.personnelId)!.add(a.date);
      }
    }
    for (const a of assignments) {
      if (!a.personnelId) continue;
      const s = a.shiftType.toLowerCase();
      if (s.includes('day') || s.includes('gunduz') || s.includes('sabah') || a.startTime < '12') {
        const prevDate = new Date(a.date);
        prevDate.setDate(prevDate.getDate() - 1);
        const prevStr = prevDate.toISOString().split('T')[0];
        const nights = nightPersonnel.get(a.personnelId);
        if (nights && nights.has(prevStr)) {
          const name = a.personnelName || a.personnelId;
          warnings.push({
            type: 'rest',
            message: `${name}: Gece ertesinde gündüz (${a.date})`,
            severity: 'error',
            date: a.date,
            deviceId: a.deviceId,
            shiftType: a.shiftType,
            alertKey: `rest|${a.id}`,
          });
        }
      }
    }

    // Weekly overload (>5 shifts in 7-day window)
    const weekMap = new Map<string, Map<string, number>>();
    for (const a of assignments) {
      if (!a.personnelId) continue;
      const d = new Date(a.date);
      const ws = new Date(d);
      ws.setDate(d.getDate() - d.getDay());
      const wk = ws.toISOString().split('T')[0];
      if (!weekMap.has(a.personnelId)) weekMap.set(a.personnelId, new Map());
      const pw = weekMap.get(a.personnelId)!;
      pw.set(wk, (pw.get(wk) || 0) + 1);
    }
    for (const [pid, wm] of weekMap) {
      for (const [wk, cnt] of wm) {
        if (cnt > 5) {
          const name = assignments.find((a) => a.personnelId === pid)?.personnelName || pid;
          warnings.push({
            type: 'overload',
            message: `${name}: ${wk} haftasında ${cnt} vardiya`,
            severity: 'warning',
            alertKey: `overload|${pid}|${wk}`,
          });
        }
      }
    }

    return warnings;
  });

  holidayAssignmentWarning = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return null;
    const year = this.scheduleStore.selectedYear();
    const month = this.scheduleStore.selectedMonth();
    const holidayDates = new Set<string>();
    const daysInMonth = new Date(year, month, 0).getDate();
    for (let d = 1; d <= daysInMonth; d++) {
      const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
      if (isHoliday(dateStr)) holidayDates.add(dateStr);
    }
    const hasHolidayAssignment = vs.schedule.assignments.some(
      (a) => a.personnelId && holidayDates.has(a.date),
    );
    return hasHolidayAssignment ? 'Resmî tatil vardiyası — ek mesai planlaması doğrulayın' : null;
  });

  holidayWarningItem = computed(() => {
    const msg = this.holidayAssignmentWarning();
    return msg
      ? [
          {
            type: 'holiday',
            message: msg,
            severity: 'warning' as const,
            alertKey: 'holiday|assignments',
          },
        ]
      : [];
  });

  allWarnings = computed(() => [
    ...this.validationWarnings().filter((w) => !this.resolvedAlerts().has(w.alertKey)),
    ...this.holidayWarningItem().filter((w) => !this.resolvedAlerts().has(w.alertKey)),
  ]);

  gridStatusSummary = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success')
      return { devices: 0, shifts: 0, assigned: 0, empty: 0, holidays: 0 };
    const devCount = vs.schedule.devices.length;
    const shifts = this.devices().reduce(
      (sum, d) => sum + Math.max(d.shifts.length, d.mode === 'vardiya' ? 2 : 1),
      0,
    );
    const assigned = vs.schedule.assignments.length;
    const kpis = this.unitKpis();
    const totalKey =
      kpis['totalSlots'] || kpis['radioSlotUsage']
        ? (kpis['totalSlots']?.value ?? kpis['radioSlotUsage']?.value ?? 0)
        : 0;
    const empty = Math.max(0, totalKey - assigned);
    const holidays = getHolidayCountForMonth(vs.schedule.year, vs.schedule.month);
    return { devices: devCount, shifts, assigned, empty, holidays };
  });

  // Export
  downloadExcel(): void {
    const vs = this.viewState();
    if (vs.status !== 'success') return;
    const token = this.auth.token() || '';
    const url = this.scheduleApi.getExportExcelUrl(
      vs.schedule.unit,
      vs.schedule.month,
      vs.schedule.year,
    );
    const a = document.createElement('a');
    a.href = url;
    a.download = `vardiya_plani_${this.unitLabel()}_${this.monthLabel().replace(' ', '_')}.xlsx`;
    fetch(url, { headers: { Authorization: `Bearer ${token}` } })
      .then((r) => r.blob())
      .then((blob) => {
        const obj = URL.createObjectURL(blob);
        a.href = obj;
        a.click();
        URL.revokeObjectURL(obj);
      })
      .catch(() => {
        window.open(url, '_blank');
      });
  }

  downloadPdf(): void {
    const vs = this.viewState();
    if (vs.status !== 'success') return;
    const token = this.auth.token() || '';
    const url = this.scheduleApi.getExportPdfUrl(
      vs.schedule.unit,
      vs.schedule.month,
      vs.schedule.year,
    );
    const a = document.createElement('a');
    a.download = `vardiya_plani_${this.unitLabel()}_${this.monthLabel().replace(' ', '_')}.pdf`;
    fetch(url, { headers: { Authorization: `Bearer ${token}` } })
      .then((r) => r.blob())
      .then((blob) => {
        const obj = URL.createObjectURL(blob);
        a.href = obj;
        a.click();
        URL.revokeObjectURL(obj);
      })
      .catch(() => {
        window.open(url, '_blank');
      });
  }

  printRoster(): void {
    window.print();
  }

  onScheduleScroll(event: Event): void {
    const el = event.target as HTMLElement;
    this.showLeftFade.set(el.scrollLeft > 8);
    this.showRightFade.set(el.scrollLeft + el.clientWidth < el.scrollWidth - 8);
  }

  unitColor = computed(() => UNIT_COLORS[this.selectedUnit()] || '#3b82f6');

  unitLabel = computed(() => {
    const labels: Record<UnitType, string> = {
      mr: 'MR',
      bt: 'BT',
      rontgen: 'RÖNTGEN',
      nukleer: 'NÜKLEER',
      onkoloji: 'ONKOLOJİ',
      supervizor: 'SÜPERVİZÖR',
    };
    return labels[this.selectedUnit()] || 'BİRİM';
  });

  setActiveTab(tab: 'device' | 'person'): void {
    this.activeTab.set(tab);
  }

  get planMonth(): number {
    return this.scheduleStore.selectedMonth();
  }

  get planYear(): number {
    return this.scheduleStore.selectedYear();
  }

  monthLabel = computed(() => {
    const months = [
      'Ocak',
      'Şubat',
      'Mart',
      'Nisan',
      'Mayıs',
      'Haziran',
      'Temmuz',
      'Ağustos',
      'Eylül',
      'Ekim',
      'Kasım',
      'Aralık',
    ];
    return `${months[this.scheduleStore.selectedMonth() - 1]} ${this.scheduleStore.selectedYear()}`;
  });

  errorMessage = computed(() => {
    const vs = this.viewState();
    return vs.status === 'error' ? vs.message : '';
  });
  errorCode = computed(() => {
    const vs = this.viewState();
    return vs.status === 'error' ? vs.code : 0;
  });
  errorEndpoint = computed(() => {
    const vs = this.viewState();
    return vs.status === 'error' ? vs.endpoint : '';
  });

  lastSyncLabel = computed(() => {
    if (!this.lastUpdated) return 'Yok';
    return this.lastUpdated.toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' });
  });

  days = computed<DayColumn[]>(() => {
    const year = this.scheduleStore.selectedYear();
    const month = this.scheduleStore.selectedMonth();
    const daysInMonth = new Date(year, month, 0).getDate();
    const dayNames = ['Pz', 'Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct'];
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return Array.from({ length: daysInMonth }, (_, i) => {
      const dayNum = i + 1;
      const date = new Date(year, month - 1, dayNum);
      const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(dayNum).padStart(2, '0')}`;
      const holiday = getHoliday(dateStr);
      const dayOfWeek = date.getDay();
      return {
        date,
        dateStr,
        dayNumber: dayNum,
        dayName: dayNames[dayOfWeek],
        dayNum: dayOfWeek,
        isWeekend: dayOfWeek === 0 || dayOfWeek === 6,
        isHoliday: !!holiday,
        holidayName: holiday?.name,
        holidayType: holiday?.type,
        isToday: date.getTime() === today.getTime(),
      };
    });
  });

  devices = computed<DeviceInfo[]>(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return [];
    const configs = vs.schedule.deviceShiftConfig || [];
    return vs.schedule.devices.map((d) => {
      const cfg = configs.find((c) => c.deviceId === d.id);
      const allShifts = cfg?.shifts || [];
      const seen = new Set<string>();
      const uniqueShifts = allShifts.filter((s) => {
        const key = `${s.type}|${s.personnelType || 'default'}`;
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
      });
      return {
        id: d.id,
        code: d.code,
        name: d.name,
        mode: d.mode as 'vardiya' | 'polyclinic',
        tripleShift: uniqueShifts.length > 2,
        shifts: uniqueShifts,
      };
    });
  });

  private currentSchedule = computed<ScheduleResponse | null>(() => {
    const vs = this.viewState();
    return vs.status === 'success' && vs.schedule.id ? vs.schedule : null;
  });

  private assignmentCache = computed(() => this.currentSchedule()?.assignments || []);

  private shiftTypeMatches(aShift: string, slot: string): boolean {
    const a = aShift.toLowerCase();
    const s = slot.toLowerCase();
    if (s === 'gunduz' || s === 'day') return a === 'day' || a.includes('gunduz');
    if (s === 'gece' || s === 'night') return a === 'night' || a.includes('gece');
    if (s === 'ikindi' || s === 'evening')
      return a === 'evening' || a.includes('ogle') || a.includes('ikindi');
    if (s === 'sabah' || s === 'morning') return a === 'morning' || a.includes('sabah');
    return a === s;
  }

  private findAssignment(
    deviceId: string,
    dateStr: string,
    shiftType: string,
    personnelType?: string | null,
  ): ShiftAssignment | null {
    const candidates = this.assignmentCache().filter(
      (a) =>
        a.deviceId === deviceId &&
        a.date === dateStr &&
        this.shiftTypeMatches(a.shiftType, shiftType),
    );
    if (candidates.length === 0) return null;
    if (!personnelType) return candidates[0];
    return candidates.find((a) => (a.personnelType || '') === personnelType) ?? null;
  }

  getAssignment(
    deviceId: string,
    dateStr: string,
    shiftType: string,
    personnelType?: string | null,
  ): { personnelId: string; personnelName: string } | null {
    const assignment = this.findAssignment(deviceId, dateStr, shiftType, personnelType);
    return assignment
      ? { personnelId: assignment.personnelId, personnelName: assignment.personnelName || '' }
      : null;
  }

  getFullAssignment(
    deviceId: string,
    dateStr: string,
    shiftType: string,
    personnelType?: string | null,
  ): ShiftAssignment | null {
    return this.findAssignment(deviceId, dateStr, shiftType, personnelType);
  }

  onHoverAssignment(
    e: MouseEvent,
    deviceId: string,
    dateStr: string,
    shiftType: string,
    personnelType?: string | null,
  ): void {
    const assignment = this.getFullAssignment(deviceId, dateStr, shiftType, personnelType);
    if (assignment) {
      this.tooltipAssignment.set(assignment);
      this.tooltipX.set(e.clientX + 12);
      this.tooltipY.set(e.clientY - 10);
      this.tooltipVisible.set(true);
    }
  }

  onMoveTooltip(e: MouseEvent): void {
    if (this.tooltipVisible()) {
      this.tooltipX.set(e.clientX + 12);
      this.tooltipY.set(e.clientY - 10);
    }
  }

  onLeaveTooltip(): void {
    this.tooltipVisible.set(false);
    this.tooltipAssignment.set(null);
  }

  getShiftLabel(shiftType: string): string {
    const map: Record<string, string> = {
      sabah: 'Sabah',
      ikindi: 'İkindi',
      gece: 'Gece',
      gunduz: 'Gündüz',
      day: 'Gündüz',
      night: 'Gece',
      ogle: 'İkindi',
      morning: 'Sabah',
    };
    const key = shiftType.toLowerCase();
    return map[key] || shiftType;
  }

  getShiftTypeClass(shiftType: string): string {
    const t = shiftType.toLowerCase();
    if (t === 'day' || t === 'gündüz' || t === 'gunduz') return 'day';
    if (t === 'evening' || t === 'ikindi' || t === 'öğle' || t === 'ogle') return 'ikindi';
    if (t === 'night' || t === 'gece') return 'night';
    if (t === 'morning' || t === 'sabah') return 'sabah';
    return 'day';
  }

  statusOptionLabel(status: string): string {
    const map: Record<string, string> = {
      planned: 'Planlandı',
      confirmed: 'Onaylandı',
      completed: 'Tamamlandı',
    };
    return map[status] || status;
  }

  // Flat assignment array for child component
  assignments = computed(() => {
    const vs = this.viewState();
    return vs.status === 'success' ? vs.schedule.assignments : [];
  });

  deviceCodeFromId = computed(() => {
    const vs = this.viewState();
    if (vs.status !== 'success') return new Map<string, string>();
    return new Map(vs.schedule.devices.map((d) => [d.id, d.code]));
  });

  unitPlanConfig = computed(() => {
    const base = UNIT_PLAN_CONFIGS[this.selectedUnit()] || UNIT_PLAN_CONFIGS['mr'];
    return {
      ...base,
      metricDefs: [
        ...base.metricDefs,
        {
          key: 'fairness',
          label: 'Adalet Skoru',
          calc: (a) => computeFairnessScore(a),
          formatter: (v) => `${v}%`,
        },
      ],
    };
  });

  unitKpis = computed(() => {
    const vs = this.viewState();
    const cfg = this.unitPlanConfig();
    if (vs.status !== 'success') {
      const entries: Record<string, { value: number; label: string; formatted: string }> = {};
      for (const d of cfg.metricDefs)
        entries[d.key] = {
          value: 0,
          label: d.label,
          formatted: d.formatter ? d.formatter(0) : '0',
        };
      return entries;
    }
    const dev = vs.schedule.devices.length;
    const entries: Record<string, { value: number; label: string; formatted: string }> = {};
    for (const d of cfg.metricDefs) {
      const v = d.calc(vs.schedule.assignments, dev, vs.schedule);
      entries[d.key] = {
        value: v,
        label: d.label,
        formatted: d.formatter ? d.formatter(v) : String(v),
      };
    }
    return entries;
  });

  getTooltipExtraFields(a: ShiftAssignment): Array<{ label: string; value: string }> {
    return this.unitPlanConfig().tooltipExtraFields.map((f) => ({
      label: f.label,
      value: f.get(a),
    }));
  }

  kpiBreakdown = computed(() => {
    const map = new Map<string, string[]>();
    const vs = this.viewState();
    if (vs.status !== 'success') return map;
    const { assignments, devices, deviceShiftConfig } = vs.schedule;
    const daysInMonth = this.days();

    const slots: Array<{ deviceId: string; type: string; mode: string; startTime: string }> = [];
    for (const d of devices) {
      const cfg = deviceShiftConfig?.find((c) => c.deviceId === d.id);
      const shifts = cfg?.shifts || [];
      const seen = new Set<string>();
      for (const s of shifts) {
        const key = `${s.type}|${s.personnelType || 'default'}`;
        if (seen.has(key)) continue;
        seen.add(key);
        slots.push({ deviceId: d.id, type: s.type, mode: d.mode, startTime: s.startTime });
      }
      if (shifts.length === 0) {
        slots.push({ deviceId: d.id, type: 'day', mode: d.mode, startTime: '08:00' });
        if (d.mode === 'vardiya')
          slots.push({ deviceId: d.id, type: 'night', mode: d.mode, startTime: '20:00' });
      }
    }

    const totalSlots = slots.length * daysInMonth.length;
    const shiftLabelMap: Record<string, string> = {
      day: 'Gündüz',
      night: 'Gece',
      evening: 'İkindi',
      morning: 'Sabah',
    };
    const totalByShift = new Map<string, number>();
    const assignedByShift = new Map<string, number>();
    for (const s of slots) {
      const key = this.normalizeShift(s.type);
      totalByShift.set(key, (totalByShift.get(key) || 0) + daysInMonth.length);
    }
    for (const a of assignments) {
      const key = this.normalizeShift(a.shiftType);
      assignedByShift.set(key, (assignedByShift.get(key) || 0) + 1);
    }
    const shiftBreakdown = [...totalByShift.keys()].map((k) => {
      const assigned = assignedByShift.get(k) || 0;
      const total = totalByShift.get(k) || 0;
      return `${shiftLabelMap[k] || k}: ${assigned}/${total}`;
    });

    map.set('assigned', shiftBreakdown);
    map.set('unassigned', shiftBreakdown);
    map.set('emptyAlarm', shiftBreakdown);
    map.set('totalSlots', [`Toplam slot: ${totalSlots}`]);
    map.set('occupancyPct', [`Dolu: ${assignments.length} / ${totalSlots}`]);
    map.set('usageRate', [`Dolu: ${assignments.length} / ${totalSlots}`]);
    map.set('fairness', computeFairnessBreakdown(assignments));

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const three = new Date(today.getTime() + 3 * 86400000);
    let critical = 0;
    for (const day of daysInMonth) {
      const dt = new Date(day.date);
      dt.setHours(0, 0, 0, 0);
      if (dt < today || dt > three) continue;
      for (const s of slots) {
        const device = this.devices().find((d) => d.id === s.deviceId);
        if (device && this.isPolyclinicClosed(device, day)) continue;
        const filled = assignments.some(
          (a) =>
            a.deviceId === s.deviceId &&
            a.date === day.dateStr &&
            this.shiftTypeMatches(a.shiftType, s.type),
        );
        if (!filled) critical++;
      }
    }
    map.set('criticalGaps', [`Önümüzdeki 3 gün boş slot: ${critical}`]);

    const holidayNames = [
      ...new Set(
        daysInMonth.filter((d) => d.isHoliday && d.holidayName).map((d) => d.holidayName as string),
      ),
    ];
    map.set('holidayCount', holidayNames.length ? holidayNames : ['Bu ayda tatil yok']);
    return map;
  });

  // ---- Context menu ----

  onContextMenu(e: {
    event: MouseEvent;
    deviceId: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    startTime?: string;
    endTime?: string;
    personnelName: string;
    personnelId?: string;
  }): void {
    this.contextMenu.set({
      visible: true,
      x: e.event.clientX,
      y: e.event.clientY,
      deviceId: e.deviceId,
      date: e.date,
      shiftType: e.shiftType,
      personnelType: e.personnelType,
      startTime: e.startTime,
      endTime: e.endTime,
      personnelName: e.personnelName,
      personnelId: e.personnelId,
    });
  }

  closeContextMenu(): void {
    this.contextMenu.set(null);
  }

  ctxEdit(): void {
    const c = this.contextMenu();
    if (!c) return;
    this.onEditAssignment(c);
    this.closeContextMenu();
  }

  ctxDelete(): void {
    const c = this.contextMenu();
    if (!c) return;
    if (c.personnelId)
      this.onDeleteAssignment({
        deviceId: c.deviceId,
        date: c.date,
        shiftType: c.shiftType,
        personnelType: c.personnelType,
        personnelId: c.personnelId,
      });
    this.closeContextMenu();
  }

  ctxCopy(): void {
    const c = this.contextMenu();
    if (!c) return;
    if (c.personnelId && c.personnelName)
      this.onCopyAssignment({
        deviceId: c.deviceId,
        date: c.date,
        shiftType: c.shiftType,
        personnelType: c.personnelType,
        personnelId: c.personnelId,
        personnelName: c.personnelName,
      });
    this.closeContextMenu();
  }

  ctxAdd(): void {
    const c = this.contextMenu();
    if (!c) return;
    this.onAddAssignment(c);
    this.closeContextMenu();
  }

  // ---- Conflicts modal ----

  openConflicts(): void {
    const vs = this.viewState();
    if (vs.status !== 'success') return;
    const map = new Map<string, Array<{ deviceId: string; date: string; shiftType: string }>>();
    for (const a of vs.schedule.assignments) {
      if (!a.personnelId) continue;
      if (!map.has(a.personnelId)) map.set(a.personnelId, []);
      map.get(a.personnelId)!.push({ deviceId: a.deviceId, date: a.date, shiftType: a.shiftType });
    }
    const conflicts: Array<{
      personName: string;
      entries: Array<{
        deviceId: string;
        deviceCode: string;
        deviceName: string;
        date: string;
        shiftType: string;
      }>;
    }> = [];
    for (const [pid, entries] of map) {
      const byDate = new Map<string, number>();
      for (const en of entries) byDate.set(en.date, (byDate.get(en.date) || 0) + 1);
      const hasConflict = [...byDate.values()].some((n) => n > 1);
      if (hasConflict) {
        const name =
          vs.schedule.assignments.find((a) => a.personnelId === pid)?.personnelName || pid;
        conflicts.push({
          personName: name,
          entries: entries.map((en) => ({
            deviceId: en.deviceId,
            deviceCode: this.deviceCodeFromId().get(en.deviceId) || en.deviceId,
            deviceName: this.deviceFullNameMap().get(en.deviceId) || '',
            date: en.date,
            shiftType: en.shiftType,
          })),
        });
      }
    }
    if (conflicts.length === 0) {
      this.notification.info(
        'Çakışma Yok',
        'Aynı gün birden fazla vardiyaya atanmış personel bulunmuyor.',
      );
      return;
    }
    this.conflictsList.set(conflicts);
    this.conflictsOpen.set(true);
  }

  closeConflicts(): void {
    this.conflictsOpen.set(false);
    this.conflictsList.set([]);
  }

  // ---- Alert resolve / dismiss ----

  private alertKeyOf(a: ScheduleAlert): string {
    return `${a.type}|${a.deviceId || ''}|${a.date || ''}|${a.message}`;
  }

  activeAlerts = computed(() =>
    this.alerts().filter((a) => !this.resolvedAlerts().has(this.alertKeyOf(a))),
  );

  onResolveAlert(e: {
    alertKey?: string;
    deviceId?: string;
    date?: string;
    shiftType?: string;
  }): void {
    if (e.alertKey) {
      this.resolvedAlerts.update((s) => new Set([...s, e.alertKey!]));
      return;
    }
    if (e.deviceId && e.date) {
      const shiftType = e.shiftType || this.firstShiftForDevice(e.deviceId);
      this.onAddAssignment({
        deviceId: e.deviceId,
        date: e.date,
        shiftType,
        personnelType: undefined,
      });
    }
  }

  private firstShiftForDevice(deviceId: string): string {
    const device = this.devices().find((d) => d.id === deviceId);
    return device?.shifts[0]?.type || 'day';
  }
  private normalizeShift(shiftType: string): string {
    const map: Record<string, string> = {
      gunduz: 'day',
      gece: 'night',
      sabah: 'morning',
      ikindi: 'evening',
      aksam: 'evening',
    };
    return map[shiftType.toLowerCase()] || shiftType;
  }

  private defaultSlotTimes(shiftType: string): { startTime: string; endTime: string } {
    const n = this.normalizeShift(shiftType);
    if (n === 'night') return { startTime: '20:00', endTime: '08:00' };
    if (n === 'evening') return { startTime: '15:00', endTime: '23:00' };
    if (n === 'morning') return { startTime: '07:30', endTime: '15:30' };
    return { startTime: '08:00', endTime: '16:00' };
  }

  onDragStart(
    e: DragEvent,
    deviceId: string,
    date: string,
    shiftType: string,
    personnelType?: string | null,
  ): void {
    const assignment = this.getAssignment(deviceId, date, shiftType, personnelType);
    const payload = {
      deviceId,
      date,
      shiftType,
      personnelId: assignment?.personnelId || '',
      personnelName: assignment?.personnelName || '',
      personnelType,
    };
    e.dataTransfer?.setData('text/plain', JSON.stringify(payload));
    this.dragState.set({
      isDragging: true,
      sourceAssignment: payload,
      targetSlot: null,
      isValid: false,
    });
  }

  private validateDropTarget(
    src: DragAssignment,
    deviceId: string,
    date: string,
    shiftType: string,
    targetPersonnelType?: string | null,
  ): { ok: boolean; message?: string } {
    const personnelId = src.personnelId;
    const personnelName = src.personnelName || 'Bu personel';

    if (!personnelId) return { ok: false, message: 'Taşınan personel bulunamadı.' };

    const sameShiftConflict = this.assignmentCache().find(
      (a) =>
        a.personnelId === personnelId && a.date === date && shiftsMatch(a.shiftType, shiftType),
    );
    if (sameShiftConflict) {
      return {
        ok: false,
        message: `${personnelName} ${formatDateTR(date)} tarihinde zaten ${shiftNameTR(shiftType)} vardiyasına atanmıştır.`,
      };
    }

    const otherShiftConflict = this.assignmentCache().find(
      (a) =>
        a.personnelId === personnelId && a.date === date && !shiftsMatch(a.shiftType, shiftType),
    );
    if (otherShiftConflict) {
      return {
        ok: false,
        message: `${personnelName} ${formatDateTR(date)} tarihinde başka bir vardiyaya atanmıştır.`,
      };
    }

    const bookedMsg = deviceBookedMessageFor(
      this.assignmentCache(),
      deviceId,
      personnelId,
      date,
      shiftType,
      targetPersonnelType || src.personnelType,
    );
    if (bookedMsg) {
      return { ok: false, message: bookedMsg };
    }

    const s = this.normalizeShift(shiftType);
    if (s !== 'night') {
      const prev = new Date(date + 'T00:00:00');
      prev.setDate(prev.getDate() - 1);
      const prevStr = prev.toISOString().split('T')[0];
      const prevNight = this.assignmentCache().find(
        (a) =>
          a.personnelId === personnelId &&
          a.date === prevStr &&
          (this.normalizeShift(a.shiftType) === 'night' || (a.startTime && a.startTime >= '20')),
      );
      if (prevNight) {
        return {
          ok: false,
          message: `${personnelName}: önceki gece vardiyasının ertesinde ${shiftNameTR(shiftType)} atanamaz (dinlenme kuralı).`,
        };
      }
    }

    return { ok: true };
  }

  onDragOver(
    e: DragEvent | undefined,
    deviceId: string,
    date: string,
    shiftType: string,
    personnelType?: string | null,
  ): void {
    e?.preventDefault();
    const s = this.dragState();
    if (!s.isDragging || !s.sourceAssignment) return;
    const check = this.validateDropTarget(
      s.sourceAssignment,
      deviceId,
      date,
      shiftType,
      personnelType,
    );
    this.dragState.set({ ...s, targetSlot: { deviceId, date, shiftType }, isValid: check.ok });
  }

  onDragLeave(): void {
    this.dragState.update((s) => ({ ...s, targetSlot: null }));
  }

  onDrop(
    e: DragEvent | undefined,
    deviceId: string,
    date: string,
    shiftType: string,
    personnelType?: string | null,
    startTime?: string,
    endTime?: string,
  ): void {
    e?.preventDefault();
    const src = this.dragState().sourceAssignment;
    const scheduleId = this.currentSchedule()?.id;
    if (src && src.personnelId && scheduleId) {
      const check = this.validateDropTarget(src, deviceId, date, shiftType, personnelType);
      if (!check.ok) {
        this.notification.warning('Atama Engellendi', check.message || 'Bu atama yapılamaz.');
        this.dragState.set({
          isDragging: false,
          sourceAssignment: null,
          targetSlot: null,
          isValid: false,
        });
        return;
      }
      const times =
        startTime && endTime ? { startTime, endTime } : this.defaultSlotTimes(shiftType);
      this.scheduleApi
        .assignPersonnel(
          scheduleId,
          {
            deviceId,
            date,
            shiftType: this.normalizeShift(shiftType),
            personnelId: src.personnelId,
            personnelType: personnelType || undefined,
            ...times,
          },
          `Drag from ${src.deviceId}/${src.date}/${src.shiftType}`,
        )
        .pipe(takeUntil(this.destroy$))
        .subscribe({
          next: (updated) => {
            if (updated) {
              const vs = this.viewState();
              if (vs.status === 'success') this.viewState.set({ ...vs, schedule: updated });
            }
          },
          error: () => {
            /* toast servis katmanında gösterilir; mevcut görünüm korunur */
          },
        });
    }
    this.dragState.set({
      isDragging: false,
      sourceAssignment: null,
      targetSlot: null,
      isValid: false,
    });
  }

  onDragEnd(): void {
    this.dragState.set({
      isDragging: false,
      sourceAssignment: null,
      targetSlot: null,
      isValid: false,
    });
  }

  ngOnInit(): void {
    this.route.data.pipe(takeUntil(this.destroy$)).subscribe((data: any) => {
      const routeUnit = data?.['unit'] as UnitType | undefined;
      if (routeUnit && routeUnit !== this.selectedUnit()) {
        this.selectedUnit.set(routeUnit);
        this.scheduleStore.setSelectedUnit(routeUnit);
      }
    });

    this.websocket.alert$.pipe(takeUntil(this.destroy$)).subscribe((data) => {
      const vs = this.viewState();
      if (vs.status === 'success' && vs.schedule.id === data.scheduleId) {
        this.alertsLoading.set(true);
        this.scheduleApi.getScheduleAlerts(data.scheduleId).subscribe({
          next: (alerts) => {
            this.alerts.set(alerts);
            this.alertsLoading.set(false);
          },
          error: () => {
            this.alertsLoading.set(false);
          },
        });
      }
    });
  }

  ngOnDestroy(): void {
    this.loadSub?.unsubscribe();
    this.destroy$.next();
    this.destroy$.complete();
  }

  private loadPlan(unit: UnitType, month: number, year: number): void {
    this.loadSub?.unsubscribe();
    this.viewState.set({ status: 'loading' });
    this.alerts.set([]);
    this.loadSub = this.scheduleApi
      .loadScheduleByUnit(unit, month, year)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (schedule) => {
          if (schedule && schedule.id) {
            this.lastUpdated = new Date();
            this.viewState.set({ status: 'success', schedule });
            this.scheduleStore.setSchedule({
              id: schedule.id,
              unit: schedule.unit,
              month: schedule.month,
              year: schedule.year,
              status: schedule.status as any,
              assignments: schedule.assignments.map((a) => ({ ...a })),
              version: schedule.version,
              createdAt: schedule.createdAt ? new Date(schedule.createdAt) : new Date(),
              updatedAt: schedule.updatedAt ? new Date(schedule.updatedAt) : new Date(),
            });
            this.alertsLoading.set(true);
            this.scheduleApi.getScheduleAlerts(schedule.id).subscribe({
              next: (alerts) => {
                this.alerts.set(alerts);
                this.alertsLoading.set(false);
              },
              error: () => {
                this.alertsLoading.set(false);
              },
            });
          } else if (schedule && !schedule.id) {
            this.viewState.set({
              status: 'empty',
              reason: `${this.unitLabel()} birimi için ${this.monthLabel()} döneminde plan bulunamadı.`,
            });
          } else {
            this.viewState.set({
              status: 'empty',
              reason: `${this.unitLabel()} birimi için ${this.monthLabel()} döneminde plan bulunamadı.`,
            });
          }
        },
        error: (err) => {
          const mapped = mapHttpError(err);
          this.viewState.set({ status: 'error', ...mapped });
        },
      });
  }

  refresh(): void {
    this.loadPlan(
      this.selectedUnit(),
      this.scheduleStore.selectedMonth(),
      this.scheduleStore.selectedYear(),
    );
  }

  // ---- Monthly assignment ----

  openMonthlyAssign(): void {
    const vs = this.viewState();
    if (vs.status !== 'success') return;
    const first = this.devices()[0];
    this.monthlyDeviceId.set(first?.id || '');
    this.monthlyShiftType.set(first?.shifts[0]?.type || '');
    this.monthlyPersonnelId.set('');
    this.monthlySearch.set('');
    this.monthlyResult.set('');
    this.showMonthlyAssign.set(true);
    this.loadMonthlyPersonnel(vs.schedule.unit);
  }

  onMonthlyDeviceChange(): void {
    const device = this.devices().find((d) => d.id === this.monthlyDeviceId());
    this.monthlyShiftType.set(device?.shifts[0]?.type || '');
  }

  private loadMonthlyPersonnel(unitType: string): void {
    this.monthlyPersonnel.set([]);
    this.api
      .get<
        {
          id: string;
          name: string;
          skills?: string[];
          unit?: { id: string; code?: string; type?: string; name?: string };
        }[]
      >('/personnel', { params: { isActive: 'true', unitId: unitType } })
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (list) => {
          const ut = unitType.toLowerCase();
          const filtered = (list || []).filter((p) => {
            if (!ut) return true;
            const u = p.unit;
            if (!u) return false;
            return u.type === ut || (u.code && u.code.toLowerCase() === ut) || u.id === unitType;
          });
          this.monthlyPersonnel.set(filtered);
        },
        error: () => this.monthlyPersonnel.set([]),
      });
  }

  closeMonthlyAssign(): void {
    this.showMonthlyAssign.set(false);
  }

  private isPolyclinicClosed(device: DeviceInfo, day: DayColumn): boolean {
    if (device.mode !== 'polyclinic') return false;
    if (day.isHoliday) return true;
    if (this.selectedUnit() === 'nukleer') return day.dayNum === 0;
    return day.isWeekend;
  }

  private isMonthlyShiftOff(device: DeviceInfo, day: DayColumn): boolean {
    return this.isPolyclinicClosed(device, day);
  }

  async applyMonthlyAssignment(): Promise<void> {
    const vs = this.viewState();
    const deviceId = this.monthlyDeviceId();
    const shiftType = this.monthlyShiftType();
    const personnelId = this.monthlyPersonnelId();
    if (vs.status !== 'success' || !vs.schedule.id || !deviceId || !shiftType || !personnelId) {
      this.monthlyResult.set('Cihaz, vardiya ve personel seçmelisiniz.');
      return;
    }
    const scheduleId = vs.schedule.id;
    const device = this.devices().find((d) => d.id === deviceId);
    const slot = device?.shifts.find((s) => s.type === shiftType);
    const normalized = this.normalizeShift(shiftType);
    const isNight = normalized === 'night';
    const startTime = slot?.startTime || (isNight ? '20:00' : '08:00');
    const endTime = slot?.endTime || (isNight ? '08:00' : '20:00');
    const year = vs.schedule.year;
    const month = vs.schedule.month;
    const daysInMonth = new Date(year, month, 0).getDate();

    this.monthlyBusy.set(true);
    this.monthlyResult.set('');
    let assigned = 0;
    let skipped = 0;
    let failed = 0;
    try {
      for (let d = 1; d <= daysInMonth; d++) {
        const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
        const day: DayColumn = this.days()[d - 1];
        if (device && this.isMonthlyShiftOff(device, day)) {
          skipped++;
          continue;
        }
        try {
          await firstValueFrom(
            this.scheduleApi.assignPersonnel(
              scheduleId,
              {
                deviceId,
                date: dateStr,
                shiftType: normalized,
                personnelId,
                personnelType: slot?.personnelType || undefined,
                startTime,
                endTime,
              },
              'Aylık atama',
            ),
          );
          assigned++;
        } catch {
          failed++;
        }
      }
      this.monthlyResult.set(
        `Tamamlandı — Atandı: ${assigned}, Kapalı gün atlandı: ${skipped}, Başarısız: ${failed}`,
      );
      this.refresh();
    } finally {
      this.monthlyBusy.set(false);
    }
  }

  // Assignment dialog state
  assignmentDialog = signal<{
    scheduleId: string;
    deviceId: string;
    deviceCode: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    startTime?: string;
    endTime?: string;
    unitType: string;
    month: number;
    year: number;
    assignmentId?: string;
    personnelId?: string;
    personnelName?: string;
  } | null>(null);

  onAddAssignment(e: {
    deviceId: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    startTime?: string;
    endTime?: string;
    assignmentId?: string;
    personnelId?: string;
    personnelName?: string;
  }): void {
    const schedule = this.currentSchedule();
    const device = schedule?.devices.find((d) => d.id === e.deviceId);
    this.assignmentDialog.set({
      scheduleId: schedule?.id || '',
      deviceId: e.deviceId,
      deviceCode: device?.code || e.deviceId,
      date: e.date,
      shiftType: e.shiftType,
      personnelType: e.personnelType,
      startTime: e.startTime,
      endTime: e.endTime,
      unitType: this.selectedUnit(),
      month: this.scheduleStore.selectedMonth(),
      year: this.scheduleStore.selectedYear(),
      assignmentId: e.assignmentId,
      personnelId: e.personnelId,
      personnelName: e.personnelName,
    });
  }

  onEditAssignment(e: {
    deviceId: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    startTime?: string;
    endTime?: string;
  }): void {
    const existing = this.getFullAssignment(e.deviceId, e.date, e.shiftType, e.personnelType);
    this.onAddAssignment({
      deviceId: e.deviceId,
      date: e.date,
      shiftType: e.shiftType,
      personnelType: e.personnelType,
      startTime: e.startTime || existing?.startTime,
      endTime: e.endTime || existing?.endTime,
      assignmentId: existing?.id,
      personnelId: existing?.personnelId,
      personnelName: existing?.personnelName,
    });
  }

  onDeleteAssignment(e: {
    deviceId: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    personnelId?: string;
  }): void {
    const scheduleId = this.currentSchedule()?.id;
    if (!scheduleId || !e.personnelId) return;
    const assignment = this.assignmentCache().find(
      (a) =>
        a.deviceId === e.deviceId &&
        a.date === e.date &&
        a.personnelId === e.personnelId &&
        (a.shiftType === this.normalizeShift(e.shiftType) ||
          a.shiftType.includes(e.shiftType.toLowerCase())),
    );
    if (!assignment || !assignment.id) return;
    this.scheduleApi
      .removeAssignment(scheduleId, assignment.id, 'Manuel silme')
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (updated) => {
          if (updated) {
            const vs = this.viewState();
            if (vs.status === 'success') this.viewState.set({ ...vs, schedule: updated });
            this.notification.success('Atama Kaldırıldı', 'Vardiya ataması başarıyla kaldırıldı.');
          }
        },
        error: () => this.notification.error('Hata', 'Atama kaldırılamadı.'),
      });
  }

  onCopyAssignment(e: {
    deviceId: string;
    date: string;
    shiftType: string;
    personnelType?: string | null;
    personnelId: string;
    personnelName: string;
  }): void {
    this.clipboardAssignment.set({
      personnelId: e.personnelId,
      personnelName: e.personnelName,
      shiftType: e.shiftType,
      personnelType: e.personnelType,
    });
    this.notification.success('Kopyalandı', `${e.personnelName} panoya kopyalandı.`);
  }

  onPasteAssignment(): void {
    const clip = this.clipboardAssignment();
    if (!clip || !this.currentSchedule()?.id) return;
    this.onAddAssignment({
      deviceId: '',
      date: '',
      shiftType: clip.shiftType,
      personnelType: clip.personnelType,
    });
  }

  onAssignmentSaved(): void {
    this.refresh();
  }

  closeAssignmentDialog(): void {
    this.assignmentDialog.set(null);
  }

  openAutoGenerate(): void {
    this.showAutoGenerate.set(true);
  }

  previousMonth(): void {
    this.scheduleStore.previousMonth();
    this.refresh();
  }

  nextMonth(): void {
    this.scheduleStore.nextMonth();
    this.refresh();
  }

  goToToday(): void {
    const now = new Date();
    this.scheduleStore.setSelectedMonth(now.getMonth() + 1, now.getFullYear());
    this.refresh();
  }

  openMonthPicker(): void {
    this.pickerMonth.set(this.scheduleStore.selectedMonth());
    this.pickerYear.set(this.scheduleStore.selectedYear());
    this.showMonthPicker.set(true);
  }

  closeMonthPicker(): void {
    this.showMonthPicker.set(false);
  }

  jumpToMonth(): void {
    this.scheduleStore.setSelectedMonth(this.pickerMonth(), this.pickerYear());
    this.showMonthPicker.set(false);
    this.refresh();
  }
}
