export const RbacRolesSeed = [
  {
    name: 'SYSTEM_ADMIN',
    label: 'Sistem Yöneticisi',
    description: 'Tüm sistem üzerinde tam erişim',
    level: 1000,
    parentName: null,
    isSystem: true,
  },
  {
    name: 'HOSPITAL_ADMIN',
    label: 'Hastane Yöneticisi',
    description: 'Hastane düzeyinde tam erişim',
    level: 800,
    parentName: 'SYSTEM_ADMIN',
    isSystem: true,
  },
  {
    name: 'IMAGING_DIRECTOR',
    label: 'Görüntüleme Hizmetleri Müdürü',
    description: 'Görüntüleme hizmetlerinin yönetimi',
    level: 600,
    parentName: 'HOSPITAL_ADMIN',
    isSystem: false,
  },
  {
    name: 'SUPERVISOR',
    label: 'Süpervizör',
    description: 'Vardiya ve personel süpervizyonu',
    level: 500,
    parentName: 'IMAGING_DIRECTOR',
    isSystem: false,
  },
  {
    name: 'MEDICAL_ENGINEER',
    label: 'Medikal Mühendis',
    description: 'Biyomedikal cihaz ve teknik mühendislik',
    level: 400,
    parentName: 'SUPERVISOR',
    isSystem: false,
  },
  {
    name: 'SENIOR_TECHNICIAN',
    label: 'Sorumlu Tekniker',
    description: 'Teknik operasyonlarda sorumlu teknisyen',
    level: 300,
    parentName: 'MEDICAL_ENGINEER',
    isSystem: false,
  },
  {
    name: 'TECHNICIAN',
    label: 'Tekniker',
    description: 'Günlük teknik operasyonlar',
    level: 200,
    parentName: 'SENIOR_TECHNICIAN',
    isSystem: false,
  },
  {
    name: 'ASSISTANT_TECHNICIAN',
    label: 'Yardımcı Tekniker',
    description: 'Teknik destek ve yardımcı operasyonlar',
    level: 150,
    parentName: 'TECHNICIAN',
    isSystem: false,
  },
  {
    name: 'SECRETARY',
    label: 'Sekreter',
    description: 'İdari ve ofis desteği',
    level: 100,
    parentName: 'ASSISTANT_TECHNICIAN',
    isSystem: false,
  },
  {
    name: 'GUEST',
    label: 'Misafir',
    description: 'Salt okunur erişim',
    level: 50,
    parentName: null,
    isSystem: false,
  },
];

export const RbacPermissionsSeed = [
  {
    name: 'users.create',
    label: 'Kullanıcı Oluştur',
    module: 'users',
    action: 'create',
  },
  {
    name: 'users.read',
    label: 'Kullanıcı Görüntüle',
    module: 'users',
    action: 'read',
  },
  {
    name: 'users.update',
    label: 'Kullanıcı Güncelle',
    module: 'users',
    action: 'update',
  },
  {
    name: 'users.delete',
    label: 'Kullanıcı Sil',
    module: 'users',
    action: 'delete',
  },

  {
    name: 'personnel.create',
    label: 'Personel Oluştur',
    module: 'personnel',
    action: 'create',
  },
  {
    name: 'personnel.read',
    label: 'Personel Görüntüle',
    module: 'personnel',
    action: 'read',
  },
  {
    name: 'personnel.update',
    label: 'Personel Güncelle',
    module: 'personnel',
    action: 'update',
  },
  {
    name: 'personnel.delete',
    label: 'Personel Sil',
    module: 'personnel',
    action: 'delete',
  },

  {
    name: 'schedule.create',
    label: 'Vardiya Oluştur',
    module: 'schedule',
    action: 'create',
  },
  {
    name: 'schedule.read',
    label: 'Vardiya Görüntüle',
    module: 'schedule',
    action: 'read',
  },
  {
    name: 'schedule.update',
    label: 'Vardiya Güncelle',
    module: 'schedule',
    action: 'update',
  },
  {
    name: 'schedule.delete',
    label: 'Vardiya Sil',
    module: 'schedule',
    action: 'delete',
  },
  {
    name: 'schedule.generate',
    label: 'Vardiya Oluştur (Algoritma)',
    module: 'schedule',
    action: 'generate',
  },
  {
    name: 'schedule.validate',
    label: 'Vardiya Doğrula',
    module: 'schedule',
    action: 'validate',
  },
  {
    name: 'schedule.submit',
    label: 'Vardiya İncelemeye Gönder',
    module: 'schedule',
    action: 'submit',
  },
  {
    name: 'schedule.approve',
    label: 'Vardiya Onayla',
    module: 'schedule',
    action: 'approve',
  },
  {
    name: 'schedule.reject',
    label: 'Vardiya Reddet',
    module: 'schedule',
    action: 'reject',
  },
  {
    name: 'schedule.publish',
    label: 'Vardiya Yayınla',
    module: 'schedule',
    action: 'publish',
  },
  {
    name: 'schedule.archive',
    label: 'Vardiya Arşivle',
    module: 'schedule',
    action: 'archive',
  },
  {
    name: 'schedule.rollback',
    label: 'Vardiya Geri Al',
    module: 'schedule',
    action: 'rollback',
  },
  {
    name: 'schedule.override',
    label: 'Vardiya Kural Override',
    module: 'schedule',
    action: 'override',
  },

  {
    name: 'attendance.read',
    label: 'Devam Görüntüle',
    module: 'attendance',
    action: 'read',
  },
  {
    name: 'attendance.manage',
    label: 'Devam Yönet',
    module: 'attendance',
    action: 'manage',
  },

  {
    name: 'training.read',
    label: 'Eğitim Görüntüle',
    module: 'training',
    action: 'read',
  },
  {
    name: 'training.manage',
    label: 'Eğitim Yönet',
    module: 'training',
    action: 'manage',
  },

  {
    name: 'analytics.read',
    label: 'Analitik Görüntüle',
    module: 'analytics',
    action: 'read',
  },

  {
    name: 'device.read',
    label: 'Cihaz Görüntüle',
    module: 'device',
    action: 'read',
  },
  {
    name: 'device.manage',
    label: 'Cihaz Yönet',
    module: 'device',
    action: 'manage',
  },

  {
    name: 'notification.manage',
    label: 'Bildirim Yönet',
    module: 'notification',
    action: 'manage',
  },

  {
    name: 'audit.read',
    label: 'Denetim Kayıtları',
    module: 'audit',
    action: 'read',
  },
  {
    name: 'audit.export',
    label: 'Denetim Dışa Aktar',
    module: 'audit',
    action: 'export',
  },

  {
    name: 'role.create',
    label: 'Rol Oluştur',
    module: 'role',
    action: 'create',
  },
  { name: 'role.read', label: 'Rol Görüntüle', module: 'role', action: 'read' },
  {
    name: 'role.update',
    label: 'Rol Güncelle',
    module: 'role',
    action: 'update',
  },
  { name: 'role.delete', label: 'Rol Sil', module: 'role', action: 'delete' },
  { name: 'role.assign', label: 'Rol Ata', module: 'role', action: 'assign' },

  {
    name: 'organization.create',
    label: 'Kuruluş Oluştur',
    module: 'organization',
    action: 'create',
  },
  {
    name: 'organization.read',
    label: 'Kuruluş Görüntüle',
    module: 'organization',
    action: 'read',
  },
  {
    name: 'organization.update',
    label: 'Kuruluş Güncelle',
    module: 'organization',
    action: 'update',
  },
  {
    name: 'organization.delete',
    label: 'Kuruluş Sil',
    module: 'organization',
    action: 'delete',
  },
  {
    name: 'organization.manage',
    label: 'Kuruluş Yönet',
    module: 'organization',
    action: 'manage',
  },

  {
    name: 'hospital.create',
    label: 'Hastane Oluştur',
    module: 'hospital',
    action: 'create',
  },
  {
    name: 'hospital.read',
    label: 'Hastane Görüntüle',
    module: 'hospital',
    action: 'read',
  },
  {
    name: 'hospital.update',
    label: 'Hastane Güncelle',
    module: 'hospital',
    action: 'update',
  },
  {
    name: 'hospital.delete',
    label: 'Hastane Sil',
    module: 'hospital',
    action: 'delete',
  },

  {
    name: 'unit.create',
    label: 'Birim Oluştur',
    module: 'unit',
    action: 'create',
  },
  {
    name: 'unit.read',
    label: 'Birim Görüntüle',
    module: 'unit',
    action: 'read',
  },
  {
    name: 'unit.update',
    label: 'Birim Güncelle',
    module: 'unit',
    action: 'update',
  },
  { name: 'unit.delete', label: 'Birim Sil', module: 'unit', action: 'delete' },

  {
    name: 'swap_request.read',
    label: 'Takas Talepleri Görüntüle',
    module: 'swap_request',
    action: 'read',
  },
  {
    name: 'swap_request.manage',
    label: 'Takas Talepleri Yönet',
    module: 'swap_request',
    action: 'manage',
  },
  {
    name: 'swap_request.approve',
    label: 'Takas Talepleri Onayla',
    module: 'swap_request',
    action: 'approve',
  },

  {
    name: 'incident.read',
    label: 'Olay Görüntüle',
    module: 'incident',
    action: 'read',
  },
  {
    name: 'incident.create',
    label: 'Olay Oluştur',
    module: 'incident',
    action: 'create',
  },
  {
    name: 'incident.update',
    label: 'Olay Güncelle',
    module: 'incident',
    action: 'update',
  },
  {
    name: 'incident.delete',
    label: 'Olay Sil',
    module: 'incident',
    action: 'delete',
  },

  {
    name: 'handover.read',
    label: 'Devir Teslim Görüntüle',
    module: 'handover',
    action: 'read',
  },
  {
    name: 'handover.create',
    label: 'Devir Teslim Oluştur',
    module: 'handover',
    action: 'create',
  },
  {
    name: 'handover.update',
    label: 'Devir Teslim Güncelle',
    module: 'handover',
    action: 'update',
  },
  {
    name: 'handover.delete',
    label: 'Devir Teslim Sil',
    module: 'handover',
    action: 'delete',
  },

  {
    name: 'asset.read',
    label: 'Demirbaş Görüntüle',
    module: 'asset',
    action: 'read',
  },
  {
    name: 'asset.create',
    label: 'Demirbaş Oluştur',
    module: 'asset',
    action: 'create',
  },
  {
    name: 'asset.update',
    label: 'Demirbaş Güncelle',
    module: 'asset',
    action: 'update',
  },
  {
    name: 'asset.delete',
    label: 'Demirbaş Sil',
    module: 'asset',
    action: 'delete',
  },
  {
    name: 'asset.transfer',
    label: 'Demirbaş Transfer',
    module: 'asset',
    action: 'transfer',
  },
  {
    name: 'asset.depreciate',
    label: 'Demirbaş Amortisman',
    module: 'asset',
    action: 'depreciate',
  },

  {
    name: 'maintenance.read',
    label: 'Bakım Kayıtları Görüntüle',
    module: 'maintenance',
    action: 'read',
  },
  {
    name: 'maintenance.create',
    label: 'Bakım Kaydı Oluştur',
    module: 'maintenance',
    action: 'create',
  },
  {
    name: 'maintenance.update',
    label: 'Bakım Kaydı Güncelle',
    module: 'maintenance',
    action: 'update',
  },
  {
    name: 'maintenance.delete',
    label: 'Bakım Kaydı Sil',
    module: 'maintenance',
    action: 'delete',
  },
  {
    name: 'maintenance.schedule',
    label: 'Bakım Planla',
    module: 'maintenance',
    action: 'schedule',
  },
  {
    name: 'maintenance.approve',
    label: 'Bakım Onayla',
    module: 'maintenance',
    action: 'approve',
  },

  {
    name: 'consumable.read',
    label: 'Sarf Malzeme Görüntüle',
    module: 'consumable',
    action: 'read',
  },
  {
    name: 'consumable.create',
    label: 'Sarf Malzeme Oluştur',
    module: 'consumable',
    action: 'create',
  },
  {
    name: 'consumable.update',
    label: 'Sarf Malzeme Güncelle',
    module: 'consumable',
    action: 'update',
  },
  {
    name: 'consumable.delete',
    label: 'Sarf Malzeme Sil',
    module: 'consumable',
    action: 'delete',
  },
  {
    name: 'consumable.stock',
    label: 'Stok Yönet',
    module: 'consumable',
    action: 'stock',
  },

  {
    name: 'inventory.read',
    label: 'Envanter Görüntüle',
    module: 'inventory',
    action: 'read',
  },
  {
    name: 'inventory.create',
    label: 'Envanter Oluştur',
    module: 'inventory',
    action: 'create',
  },
  {
    name: 'inventory.update',
    label: 'Envanter Güncelle',
    module: 'inventory',
    action: 'update',
  },
  {
    name: 'inventory.delete',
    label: 'Envanter Sil',
    module: 'inventory',
    action: 'delete',
  },
  {
    name: 'inventory.count',
    label: 'Envanter Sayım',
    module: 'inventory',
    action: 'count',
  },
  {
    name: 'inventory.transfer',
    label: 'Envanter Transfer',
    module: 'inventory',
    action: 'transfer',
  },
  {
    name: 'inventory.adjust',
    label: 'Envanter Düzelt',
    module: 'inventory',
    action: 'adjust',
  },
  {
    name: 'inventory.consume',
    label: 'Tüketim Kaydet',
    module: 'inventory',
    action: 'consume',
  },
  {
    name: 'inventory.waste',
    label: 'Atık Kaydet',
    module: 'inventory',
    action: 'waste',
  },
  {
    name: 'inventory.alert',
    label: 'Stok Uyarıları Yönet',
    module: 'inventory',
    action: 'alert',
  },

  {
    name: 'procurement.read',
    label: 'Satın Alma Görüntüle',
    module: 'procurement',
    action: 'read',
  },
  {
    name: 'procurement.create',
    label: 'Satın Alma Talebi Oluştur',
    module: 'procurement',
    action: 'create',
  },
  {
    name: 'procurement.update',
    label: 'Satın Alma Güncelle',
    module: 'procurement',
    action: 'update',
  },
  {
    name: 'procurement.delete',
    label: 'Satın Alma Sil',
    module: 'procurement',
    action: 'delete',
  },
  {
    name: 'procurement.approve',
    label: 'Satın Alma Onayla',
    module: 'procurement',
    action: 'approve',
  },
  {
    name: 'procurement.order',
    label: 'Sipariş Oluştur',
    module: 'procurement',
    action: 'order',
  },

  {
    name: 'contract.read',
    label: 'Sözleşme Görüntüle',
    module: 'contract',
    action: 'read',
  },
  {
    name: 'contract.create',
    label: 'Sözleşme Oluştur',
    module: 'contract',
    action: 'create',
  },
  {
    name: 'contract.update',
    label: 'Sözleşme Güncelle',
    module: 'contract',
    action: 'update',
  },
  {
    name: 'contract.delete',
    label: 'Sözleşme Sil',
    module: 'contract',
    action: 'delete',
  },
  {
    name: 'contract.approve',
    label: 'Sözleşme Onayla',
    module: 'contract',
    action: 'approve',
  },
  {
    name: 'contract.renew',
    label: 'Sözleşme Yenile',
    module: 'contract',
    action: 'renew',
  },

  {
    name: 'supplier.read',
    label: 'Tedarikçi Görüntüle',
    module: 'supplier',
    action: 'read',
  },
  {
    name: 'supplier.create',
    label: 'Tedarikçi Oluştur',
    module: 'supplier',
    action: 'create',
  },
  {
    name: 'supplier.update',
    label: 'Tedarikçi Güncelle',
    module: 'supplier',
    action: 'update',
  },
  {
    name: 'supplier.delete',
    label: 'Tedarikçi Sil',
    module: 'supplier',
    action: 'delete',
  },
  {
    name: 'supplier.evaluate',
    label: 'Tedarikçi Değerlendir',
    module: 'supplier',
    action: 'evaluate',
  },

  {
    name: 'quality.read',
    label: 'Kalite Kayıtları Görüntüle',
    module: 'quality',
    action: 'read',
  },
  {
    name: 'quality.create',
    label: 'Kalite Kaydı Oluştur',
    module: 'quality',
    action: 'create',
  },
  {
    name: 'quality.update',
    label: 'Kalite Kaydı Güncelle',
    module: 'quality',
    action: 'update',
  },
  {
    name: 'quality.delete',
    label: 'Kalite Kaydı Sil',
    module: 'quality',
    action: 'delete',
  },
  {
    name: 'quality.approve',
    label: 'Kalite Onayla',
    module: 'quality',
    action: 'approve',
  },

  {
    name: 'radiation.read',
    label: 'Radyasyon Kayıtları Görüntüle',
    module: 'radiation',
    action: 'read',
  },
  {
    name: 'radiation.create',
    label: 'Radyasyon Kaydı Oluştur',
    module: 'radiation',
    action: 'create',
  },
  {
    name: 'radiation.update',
    label: 'Radyasyon Kaydı Güncelle',
    module: 'radiation',
    action: 'update',
  },
  {
    name: 'radiation.delete',
    label: 'Radyasyon Kaydı Sil',
    module: 'radiation',
    action: 'delete',
  },
  {
    name: 'radiation.monitor',
    label: 'Dozimetre İzle',
    module: 'radiation',
    action: 'monitor',
  },

  {
    name: 'lifecycle.read',
    label: 'Cihaz Yaşam Döngüsü Görüntüle',
    module: 'lifecycle',
    action: 'read',
  },
  {
    name: 'lifecycle.create',
    label: 'Cihaz Yaşam Döngüsü Oluştur',
    module: 'lifecycle',
    action: 'create',
  },
  {
    name: 'lifecycle.update',
    label: 'Cihaz Yaşam Döngüsü Güncelle',
    module: 'lifecycle',
    action: 'update',
  },
  {
    name: 'lifecycle.delete',
    label: 'Cihaz Yaşam Döngüsü Sil',
    module: 'lifecycle',
    action: 'delete',
  },

  {
    name: 'supervisor-center.read',
    label: 'Süpervizör Merkezi Görüntüle',
    module: 'supervisor-center',
    action: 'read',
  },
  {
    name: 'supervisor-center.manage',
    label: 'Süpervizör Merkezi Yönet',
    module: 'supervisor-center',
    action: 'manage',
  },

  {
    name: 'calibration.read',
    label: 'Kalibrasyon Görüntüle',
    module: 'calibration',
    action: 'read',
  },
  {
    name: 'calibration.create',
    label: 'Kalibrasyon Oluştur',
    module: 'calibration',
    action: 'create',
  },
  {
    name: 'calibration.update',
    label: 'Kalibrasyon Güncelle',
    module: 'calibration',
    action: 'update',
  },
  {
    name: 'calibration.delete',
    label: 'Kalibrasyon Sil',
    module: 'calibration',
    action: 'delete',
  },
  {
    name: 'calibration.complete',
    label: 'Kalibrasyon Tamamla',
    module: 'calibration',
    action: 'complete',
  },

  {
    name: 'fault.read',
    label: 'Arıza Kayıtları Görüntüle',
    module: 'fault',
    action: 'read',
  },
  {
    name: 'fault.stats',
    label: 'Arıza İstatistikleri',
    module: 'fault',
    action: 'stats',
  },

  {
    name: 'device-history.read',
    label: 'Cihaz Servis Geçmişi',
    module: 'device-history',
    action: 'read',
  },

  {
    name: 'biomedical-kpi.read',
    label: 'Biyomedikal KPI',
    module: 'biomedical-kpi',
    action: 'read',
  },
];

export const RbacRolePermissionSeed: Record<string, string[]> = {
  SYSTEM_ADMIN: [
    'users.create',
    'users.read',
    'users.update',
    'users.delete',
    'personnel.create',
    'personnel.read',
    'personnel.update',
    'personnel.delete',
    'schedule.create',
    'schedule.read',
    'schedule.update',
    'schedule.delete',
    'schedule.generate',
    'schedule.validate',
    'schedule.submit',
    'schedule.approve',
    'schedule.reject',
    'schedule.publish',
    'schedule.archive',
    'schedule.rollback',
    'schedule.override',
    'attendance.read',
    'attendance.manage',
    'training.read',
    'training.manage',
    'analytics.read',
    'device.read',
    'device.manage',
    'notification.manage',
    'audit.read',
    'audit.export',
    'role.create',
    'role.read',
    'role.update',
    'role.delete',
    'role.assign',
    'organization.create',
    'organization.read',
    'organization.update',
    'organization.delete',
    'organization.manage',
    'hospital.create',
    'hospital.read',
    'hospital.update',
    'hospital.delete',
    'unit.create',
    'unit.read',
    'unit.update',
    'unit.delete',
    'swap_request.read',
    'swap_request.manage',
    'swap_request.approve',
    'incident.read',
    'incident.create',
    'incident.update',
    'incident.delete',
    'handover.read',
    'handover.create',
    'handover.update',
    'handover.delete',
    'asset.read',
    'asset.create',
    'asset.update',
    'asset.delete',
    'asset.transfer',
    'asset.depreciate',
    'maintenance.read',
    'maintenance.create',
    'maintenance.update',
    'maintenance.delete',
    'maintenance.schedule',
    'maintenance.approve',
    'consumable.read',
    'consumable.create',
    'consumable.update',
    'consumable.delete',
    'consumable.stock',
    'inventory.read',
    'inventory.create',
    'inventory.update',
    'inventory.delete',
    'inventory.count',
    'inventory.transfer',
    'inventory.adjust',
    'inventory.consume',
    'inventory.waste',
    'inventory.alert',
    'procurement.read',
    'procurement.create',
    'procurement.update',
    'procurement.delete',
    'procurement.approve',
    'procurement.order',
    'contract.read',
    'contract.create',
    'contract.update',
    'contract.delete',
    'contract.approve',
    'contract.renew',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'supplier.delete',
    'supplier.evaluate',
    'quality.read',
    'quality.create',
    'quality.update',
    'quality.delete',
    'quality.approve',
    'radiation.read',
    'radiation.create',
    'radiation.update',
    'radiation.delete',
    'radiation.monitor',
    'lifecycle.read',
    'lifecycle.create',
    'lifecycle.update',
    'lifecycle.delete',
    'supervisor-center.read',
    'supervisor-center.manage',
    'calibration.read',
    'calibration.create',
    'calibration.update',
    'calibration.delete',
    'calibration.complete',
    'fault.read',
    'fault.stats',
    'device-history.read',
    'biomedical-kpi.read',
  ],
  HOSPITAL_ADMIN: [
    'users.create',
    'users.read',
    'users.update',
    'users.delete',
    'personnel.create',
    'personnel.read',
    'personnel.update',
    'personnel.delete',
    'schedule.create',
    'schedule.read',
    'schedule.update',
    'schedule.delete',
    'schedule.generate',
    'schedule.validate',
    'schedule.submit',
    'schedule.approve',
    'schedule.reject',
    'schedule.publish',
    'schedule.archive',
    'schedule.rollback',
    'schedule.override',
    'attendance.read',
    'attendance.manage',
    'training.read',
    'training.manage',
    'analytics.read',
    'device.read',
    'device.manage',
    'notification.manage',
    'audit.read',
    'audit.export',
    'role.read',
    'role.assign',
    'organization.read',
    'organization.update',
    'hospital.create',
    'hospital.read',
    'hospital.update',
    'hospital.delete',
    'unit.create',
    'unit.read',
    'unit.update',
    'unit.delete',
    'swap_request.read',
    'swap_request.manage',
    'swap_request.approve',
    'incident.read',
    'incident.create',
    'incident.update',
    'incident.delete',
    'handover.read',
    'handover.create',
    'handover.update',
    'handover.delete',
    'asset.read',
    'asset.create',
    'asset.update',
    'asset.delete',
    'asset.transfer',
    'asset.depreciate',
    'maintenance.read',
    'maintenance.create',
    'maintenance.update',
    'maintenance.delete',
    'maintenance.schedule',
    'maintenance.approve',
    'consumable.read',
    'consumable.create',
    'consumable.update',
    'consumable.delete',
    'consumable.stock',
    'inventory.read',
    'inventory.create',
    'inventory.update',
    'inventory.delete',
    'inventory.count',
    'inventory.transfer',
    'inventory.adjust',
    'inventory.consume',
    'inventory.waste',
    'inventory.alert',
    'procurement.read',
    'procurement.create',
    'procurement.update',
    'procurement.delete',
    'procurement.approve',
    'procurement.order',
    'contract.read',
    'contract.create',
    'contract.update',
    'contract.delete',
    'contract.approve',
    'contract.renew',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'supplier.delete',
    'supplier.evaluate',
    'quality.read',
    'quality.create',
    'quality.update',
    'quality.delete',
    'quality.approve',
    'radiation.read',
    'radiation.create',
    'radiation.update',
    'radiation.delete',
    'radiation.monitor',
    'lifecycle.read',
    'lifecycle.create',
    'lifecycle.update',
    'lifecycle.delete',
    'supervisor-center.read',
    'supervisor-center.manage',
    'calibration.read',
    'calibration.create',
    'calibration.update',
    'calibration.delete',
    'calibration.complete',
    'fault.read',
    'fault.stats',
    'device-history.read',
    'biomedical-kpi.read',
  ],
  IMAGING_DIRECTOR: [
    'users.read',
    'personnel.read',
    'personnel.update',
    'schedule.create',
    'schedule.read',
    'schedule.update',
    'schedule.generate',
    'schedule.validate',
    'schedule.submit',
    'schedule.approve',
    'schedule.reject',
    'schedule.publish',
    'schedule.archive',
    'schedule.rollback',
    'attendance.read',
    'attendance.manage',
    'training.read',
    'training.manage',
    'analytics.read',
    'device.read',
    'device.manage',
    'notification.manage',
    'audit.read',
    'role.read',
    'unit.read',
    'swap_request.read',
    'swap_request.manage',
    'swap_request.approve',
    'incident.read',
    'incident.create',
    'incident.update',
    'handover.read',
    'handover.create',
    'handover.update',
    'asset.read',
    'asset.create',
    'asset.update',
    'asset.transfer',
    'maintenance.read',
    'maintenance.create',
    'maintenance.update',
    'maintenance.schedule',
    'maintenance.approve',
    'consumable.read',
    'consumable.create',
    'consumable.update',
    'consumable.stock',
    'inventory.read',
    'inventory.update',
    'procurement.read',
    'procurement.create',
    'procurement.update',
    'procurement.approve',
    'contract.read',
    'contract.create',
    'contract.update',
    'contract.approve',
    'contract.renew',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'supplier.evaluate',
    'quality.read',
    'quality.create',
    'quality.update',
    'quality.approve',
    'radiation.read',
    'radiation.create',
    'radiation.update',
    'radiation.monitor',
    'lifecycle.read',
    'lifecycle.create',
    'supervisor-center.read',
    'supervisor-center.manage',
    'calibration.read',
    'calibration.create',
    'calibration.update',
    'calibration.complete',
    'fault.read',
    'fault.stats',
    'device-history.read',
    'biomedical-kpi.read',
  ],
  SUPERVISOR: [
    'personnel.read',
    'schedule.create',
    'schedule.read',
    'schedule.update',
    'schedule.generate',
    'schedule.validate',
    'schedule.submit',
    'schedule.approve',
    'schedule.override',
    'attendance.read',
    'attendance.manage',
    'training.read',
    'analytics.read',
    'device.read',
    'device.manage',
    'notification.manage',
    'audit.read',
    'unit.read',
    'swap_request.read',
    'swap_request.manage',
    'swap_request.approve',
    'incident.read',
    'incident.create',
    'incident.update',
    'handover.read',
    'handover.create',
    'handover.update',
    'asset.read',
    'asset.create',
    'asset.update',
    'maintenance.read',
    'maintenance.create',
    'maintenance.update',
    'consumable.read',
    'inventory.read',
    'radiation.read',
    'lifecycle.read',
    'supervisor-center.read',
    'supervisor-center.manage',
    'calibration.read',
    'calibration.create',
    'calibration.complete',
    'fault.read',
    'fault.stats',
    'device-history.read',
    'biomedical-kpi.read',
  ],
  MEDICAL_ENGINEER: [
    'personnel.read',
    'schedule.read',
    'schedule.update',
    'schedule.validate',
    'attendance.read',
    'device.read',
    'device.manage',
    'unit.read',
    'swap_request.read',
    'incident.read',
    'incident.create',
    'incident.update',
    'handover.read',
    'handover.create',
    'asset.read',
    'asset.create',
    'asset.update',
    'asset.transfer',
    'maintenance.read',
    'maintenance.create',
    'maintenance.update',
    'maintenance.schedule',
    'consumable.read',
    'consumable.create',
    'consumable.update',
    'consumable.stock',
    'inventory.read',
    'inventory.update',
    'inventory.count',
    'inventory.consume',
    'inventory.alert',
    'radiation.read',
    'radiation.monitor',
    'lifecycle.read',
    'lifecycle.create',
    'lifecycle.update',
    'calibration.read',
    'calibration.create',
    'calibration.update',
    'calibration.complete',
    'fault.read',
    'fault.stats',
    'device-history.read',
    'biomedical-kpi.read',
  ],
  SENIOR_TECHNICIAN: [
    'personnel.read',
    'schedule.read',
    'schedule.update',
    'attendance.read',
    'device.read',
    'unit.read',
    'swap_request.read',
    'swap_request.manage',
    'incident.read',
    'incident.create',
    'incident.update',
    'handover.read',
    'handover.create',
    'asset.read',
    'maintenance.read',
    'maintenance.create',
    'consumable.read',
    'inventory.read',
    'radiation.read',
    'lifecycle.read',
    'calibration.read',
    'fault.read',
    'device-history.read',
  ],
  TECHNICIAN: [
    'personnel.read',
    'schedule.read',
    'attendance.read',
    'device.read',
    'incident.read',
    'incident.create',
    'handover.read',
    'handover.create',
    'asset.read',
    'maintenance.read',
    'consumable.read',
    'inventory.read',
    'radiation.read',
    'calibration.read',
    'fault.read',
    'device-history.read',
  ],
  ASSISTANT_TECHNICIAN: [
    'schedule.read',
    'attendance.read',
    'device.read',
    'incident.read',
    'incident.create',
    'handover.read',
    'asset.read',
    'maintenance.read',
    'consumable.read',
    'radiation.read',
  ],
  SECRETARY: [
    'personnel.read',
    'schedule.read',
    'attendance.read',
    'training.read',
    'device.read',
    'unit.read',
    'incident.read',
    'handover.read',
    'asset.read',
    'consumable.read',
  ],
  GUEST: ['schedule.read', 'device.read', 'unit.read'],
};
