{{- if .Values.serviceAccounts }}
{{- range $name, $cfg := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vardiya.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vardiya.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
automountServiceAccountToken: {{ $cfg.automountServiceAccountToken | default false }}
{{- end }}
{{- end }}
