apiVersion: v1
kind: Secret
metadata:
  name: repo-vardiya-git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: vardiya
stringData:
  type: git
  url: https://github.com/anomalyco/vardiyasystem.git
  project: vardiya
  name: vardiya-git
  insecure: "false"
  enableLfs: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-vardiya-helm-bitnami
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: vardiya
stringData:
  type: helm
  url: https://charts.bitnami.com/bitnami
  project: vardiya
  name: bitnami
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-vardiya-helm-prometheus
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: vardiya
stringData:
  type: helm
  url: https://prometheus-community.github.io/helm-charts
  project: vardiya
  name: prometheus-community
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-vardiya-helm-grafana
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: vardiya
stringData:
  type: helm
  url: https://grafana.github.io/helm-charts
  project: vardiya
  name: grafana
