apiVersion: v1
kind: Service
metadata:
  name: {{ include "vardiya.fullname" . }}-postgres
  labels: {{- include "vardiya.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
