import type { UnitType } from '../enums';

export const CONSTRAINT_RULES = {
  WORK_LAW: {
    WRK001: {
      id: 'WRK001',
      name: 'Haftalık Çalışma Süresi',
      description: 'Haftalık toplam çalışma süresi sınırı',
      minHours: 0,
      maxHours: 45,
      type: 'hard' as const,
      priority: 1,
      unit: null,
    },
    WRK002: {
      id: 'WRK002',
      name: 'Günlük Çalışma Süresi',
      description: 'Sağlık sektöründe vardiya istisnai planlama ile günlük max 11 saat',
      minHours: 0,
      maxHours: 11,
      type: 'hard' as const,
      priority: 1,
      unit: null,
    },
    WRK003: {
      id: 'WRK003',
      name: 'Vardiyalar Arası Dinlenme',
      description: 'İki vardiya arasında minimum 11 saat dinlenme (4857 SK m.46)',
      minRestHours: 11,
      type: 'hard' as const,
      priority: 1,
      unit: null,
    },
    WRK004: {
      id: 'WRK004',
      name: 'Haftalık Kesintisiz İzin',
      description: 'Haftada minimum 24 saat kesintisiz dinlenme hakkı',
      minRestHours: 24,
      type: 'hard' as const,
      priority: 1,
      unit: null,
    },
    WRK005: {
      id: 'WRK005',
      name: 'Aynı Gün Çift Vardiya',
      description: 'Aynı gün içinde iki farklı vardiyada çalışma yasak',
      maxShiftsPerDay: 1,
      type: 'hard' as const,
      priority: 1,
      unit: null,
    },
  },

  SHIFT_RULES: {
    SHIFT001: {
      id: 'SHIFT001',
      name: 'Gündüz → Aynı Gece Yasak',
      description: 'Gündüz vardiyasından sonra aynı gün gece vardiyası atanamaz',
      type: 'hard' as const,
      priority: 2,
      unit: ['mr', 'bt', 'rontgen', 'nukleer'],
    },
    SHIFT002: {
      id: 'SHIFT002',
      name: 'Gece → Aynı Gündüz Kesin Yasak',
      description: 'Gece vardiyası sonrası ertesi gün gündüz çalışma kesinlikle yasak',
      type: 'hard' as const,
      priority: 2,
      unit: ['mr', 'bt', 'rontgen', 'nukleer'],
    },
    SHIFT003: {
      id: 'SHIFT003',
      name: 'Gece Sonrası Recovery',
      description: 'Gece vardiyası sonrası minimum 24 saat dinlenme önerilir',
      recommendedRecoveryHours: 24,
      minRecoveryHours: 11,
      type: 'soft' as const,
      priority: 3,
      unit: ['mr', 'bt', 'rontgen'],
    },
  },

  MR_UNIT: {
    MR001: {
      id: 'MR001',
      name: 'MR Max Ardışık Gece',
      description: 'MR bölümünde maksimum ardışık 2 gece vardiyası',
      maxConsecutiveNights: 2,
      recommendedConsecutiveNights: 1,
      type: 'hard' as const,
      priority: 3,
      unit: 'mr' as UnitType,
    },
    MR002: {
      id: 'MR002',
      name: 'MR Haftalık Max Vardiya',
      description: 'MR bölümünde haftalık maximum vardiya sayısı',
      maxShiftsPerWeek: 4,
      type: 'hard' as const,
      priority: 3,
      unit: 'mr' as UnitType,
    },
    MR003: {
      id: 'MR003',
      name: 'MR Aylık Gece Adaleti',
      description: 'MR teknisyenleri arasında aylık gece vardiyası farkı ±1 olmalı',
      maxNightDifference: 1,
      type: 'soft' as const,
      priority: 5,
      unit: 'mr' as UnitType,
    },
    MR004: {
      id: 'MR004',
      name: 'MR Mental Fatigue Threshold',
      description: 'MR mental yorgunluk eşiği - ardışık gece sonrası hata riski',
      fatigueThreshold: 3,
      type: 'warning' as const,
      priority: 4,
      unit: 'mr' as UnitType,
    },
  },

  BT_RONTGEN: {
    RAD001: {
      id: 'RAD001',
      name: 'Dozimetre Taşıma Zorunluluğu',
      description: 'BT/Röntgen çalışanları dozimetre taşımak zorundadır',
      requiresDosimetry: true,
      type: 'hard' as const,
      priority: 2,
      unit: ['bt', 'rontgen'],
    },
    RAD002: {
      id: 'RAD002',
      name: 'Yıllık Doz Limiti',
      description: 'NDK yıllık etkin doz limiti: 20 mSv/yıl',
      annualDoseLimit: 20,
      type: 'hard' as const,
      priority: 2,
      unit: ['bt', 'rontgen'],
    },
    RAD003: {
      id: 'RAD003',
      name: 'Doz Eşiği - Vardiya Azaltımı',
      description: 'Aylık doz 16mSv (yıllık %80) üzerinde gece vardiyası azaltılır',
      monthlyThreshold80: 16,
      action: 'reduce_night' as const,
      type: 'hard' as const,
      priority: 2,
      unit: ['bt', 'rontgen'],
    },
    RAD004: {
      id: 'RAD004',
      name: 'Doz Eşiği - Kritik Uyarı',
      description: 'Aylık doz 18mSv üzerinde sadece gündüz vardiyası',
      monthlyThreshold90: 18,
      action: 'day_only' as const,
      type: 'hard' as const,
      priority: 1,
      unit: ['bt', 'rontgen'],
    },
    RAD005: {
      id: 'RAD005',
      name: 'Yüksek Doz Sonrası Recovery',
      description: 'Yüksek doz alan personel için recovery boost zorunlu',
      highDoseRecoveryBoost: 48,
      type: 'hard' as const,
      priority: 3,
      unit: ['bt', 'rontgen'],
    },
    RAD006: {
      id: 'RAD006',
      name: 'Rotasyon Zorunluluğu',
      description: 'Radyasyon maruziyetini dengelemek için rotasyon zorunlu',
      requiresRotation: true,
      type: 'hard' as const,
      priority: 3,
      unit: ['bt', 'rontgen'],
    },
  },

  NUKLEER_TIP: {
    NUC001: {
      id: 'NUC001',
      name: 'Ardışık Çalışma Gün Limiti',
      description: "Nükleer Tıp'ta maksimum 5 ardışık gün çalışma",
      maxConsecutiveDays: 5,
      type: 'hard' as const,
      priority: 2,
      unit: 'nukleer' as UnitType,
    },
    NUC002: {
      id: 'NUC002',
      name: 'Cumartesi-Pazar Kuralı',
      description: 'Cumartesi çalışma sonrası Pazar tamamen serbest',
      requireSundayOff: true,
      saturdayWorkRequiresSundayOff: true,
      type: 'hard' as const,
      priority: 2,
      unit: 'nukleer' as UnitType,
    },
    NUC003: {
      id: 'NUC003',
      name: 'Gece Vardiyası Yok',
      description: "Nükleer Tıp'ta gece vardiyası bulunmaz",
      nightShiftAllowed: false,
      type: 'hard' as const,
      priority: 1,
      unit: 'nukleer' as UnitType,
    },
    NUC004: {
      id: 'NUC004',
      name: 'Min Dinlenme Süresi',
      description: 'Nükleer Tıp için minimum 16 saat dinlenme',
      minRestHours: 16,
      type: 'hard' as const,
      priority: 1,
      unit: 'nukleer' as UnitType,
    },
    NUC005: {
      id: 'NUC005',
      name: 'Rotasyon Zorunlu',
      description: 'Kontrollü alan rotasyonu zorunlu',
      requiresRotation: true,
      type: 'hard' as const,
      priority: 2,
      unit: 'nukleer' as UnitType,
    },
    NUC006: {
      id: 'NUC006',
      name: 'Radyoaktif Materyal Erişimi',
      description: 'Sadece lisanslı personel radyoaktif materyale erişebilir',
      requiresLicense: true,
      type: 'hard' as const,
      priority: 1,
      unit: 'nukleer' as UnitType,
    },
  },

  PERSONNEL_PROTECTION: {
    PROT001: {
      id: 'PROT001',
      name: 'Hamile Personel Koruması',
      description: 'Hamile personel radyasyonlu birimlerden çıkarılır',
      restriction: 'radiation_unit_block' as const,
      type: 'hard' as const,
      priority: 1,
      unit: ['bt', 'rontgen', 'nukleer'],
    },
    PROT002: {
      id: 'PROT002',
      name: '18 Yaş Altı Yasağı',
      description: '18 yaşından küçük personel radyasyonlu birimlerde çalışamaz',
      minAge: 18,
      type: 'hard' as const,
      priority: 1,
      unit: ['bt', 'rontgen', 'nukleer'],
    },
    PROT003: {
      id: 'PROT003',
      name: 'Dozimetre Teslim Zorunluluğu',
      description: 'Dozimetre teslim etmeyen personele atama yapılamaz',
      requiresDosimetryReturn: true,
      type: 'hard' as const,
      priority: 2,
      unit: ['bt', 'rontgen', 'nukleer'],
    },
    PROT004: {
      id: 'PROT004',
      name: 'Periyodik Sağlık Kontrolü',
      description: 'Sağlık kontrolü süresi dolan personele uyarı + soft block',
      checkHealthCertificate: true,
      type: 'soft' as const,
      priority: 4,
      unit: ['bt', 'rontgen', 'nukleer', 'mr'],
    },
  },
} as const;

export const SCHEDULING_PRIORITY_MATRIX = [
  {
    priority: 1,
    category: 'Yasal Uygunluk',
    rules: [
      'WRK001',
      'WRK002',
      'WRK003',
      'WRK004',
      'WRK005',
      'NUC003',
      'NUC004',
      'PROT001',
      'PROT002',
    ],
  },
  {
    priority: 2,
    category: 'Radyasyon Güvenliği',
    rules: [
      'SHIFT001',
      'SHIFT002',
      'RAD001',
      'RAD002',
      'RAD003',
      'RAD004',
      'RAD005',
      'NUC001',
      'NUC005',
      'NUC006',
      'PROT003',
    ],
  },
  { priority: 3, category: 'Dinlenme Süresi', rules: ['SHIFT003', 'MR001', 'MR002', 'RAD006'] },
  { priority: 4, category: 'Yetkinlik', rules: ['PROT004', 'MR004'] },
  { priority: 5, category: 'Adalet Dağılımı', rules: ['MR003'] },
  { priority: 6, category: 'Personel Tercihi', rules: [] },
] as const;

export const SHIFT_CONSECUTIVE_NIGHT_LIMITS: Record<
  UnitType,
  { max: number; recommended: number }
> = {
  mr: { max: 2, recommended: 1 },
  bt: { max: 3, recommended: 2 },
  rontgen: { max: 3, recommended: 2 },
  nukleer: { max: 0, recommended: 0 },
  onkoloji: { max: 2, recommended: 1 },
  supervizor: { max: 2, recommended: 1 },
};

export const RADIATION_DOSE_THRESHOLDS = {
  monthly80: 16,
  monthly90: 18,
  annualLimit: 20,
  criticalThreshold: 50,
} as const;

export const FATIGUE_COEFFICIENTS = {
  consecutiveNightPenalty: 0.15,
  weekendShiftPenalty: 0.08,
  holidayShiftPenalty: 0.12,
  shortRestPenalty: 0.2,
  overtimePenalty: 0.1,
  consecutiveDaysPenalty: 0.05,
} as const;

export const WORKLOAD_LIMITS = {
  maxWeeklyShifts: 6,
  maxNightShiftsPerWeek: 3,
  maxConsecutiveDays: 6,
  minRecoveryHoursAfterNight: 24,
  minRecoveryHoursLegal: 11,
} as const;
